### ISSUE TITLE
Don't use backslashes in file paths on windows

### ISSUE THREAD

**Issue by fabyeah** [fourseven/meteor-scss#100]
On windows, the package will auto-add filepaths with backslashes. But using backslashes is not cross platform compatible?
I'm dual booting windows and linux. I use linux to build the android app, as that isn't supported yet by meteor on windows. On Linux I get an error when using backslashes, so I have to change them to forward slashes. But on windows, if you use forward slashes, the package will add the path again with backslashes, so the files are imported twice.

    @import "styles/mystyles.scss"

turns into

    @import "styles/mystyles.scss"
    @import "styles\mystyles.scss"

**Comment by bompi88** [comment]
+1

**Comment by Octopixell** [comment]
+1 maybe it'll help fixing this issue too? #94

**Comment by fourseven** [comment]
3.2.0 is released, please let me know if there's still an issue. You may need to re-write the index.scss file you use to utilize `/` instead of `\`

**Comment by fabyeah** [comment]
Seem to be fixed in 3.2.0! Thanks so much!
