### ISSUE TITLE
includePaths inside a package

### ISSUE THREAD

**Issue by sungwoncho** [fourseven/meteor-scss#101]
I would like to know how to use `includePaths` inside a package to import a SCSS file provided by another package.

For instance, I want to import Bourbon using [Meteor-Bourbon](https://github.com/wolvesio/meteor-bourbon/). So I added this `scss.json` in my package's root, and required it in `package.js`:

```json
{
  "includePaths": [
    ".meteor/local/build/programs/server/assets/packages/wolves_bourbon",
    ".meteor/local/build/programs/server/assets/packages/wolves_neat"
  ]
}
```

However, it does not work. Any workaround?

**Comment by jhuenges** [comment]
:+1:

**Comment by timche** [comment]
1. Use `[meteor-bower](https://github.com/mquandalle/meteor-bower)` instead of `wolves:bourbon` and install `bourbon` as a bower dependency in your package. wolves:bourbon doesn't install before the stylesheets getting compiled (I don't know why), but bower does.

This is my `bower.json` inside the package's root directory for example:
```json
{
  "name": "<project-name>",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "bourbon": "4.2.3"
  }
}
```

And `.bowerrc` to tell bower where to install the dependencies:
```json
{
  "directory": "../../.meteor/local/bower"
}
```

2. You need to use the relative path in scss.json:
```json
"includePaths": [
    "../../.meteor/local/bower/bourbon/app/assets/stylesheets"
  ]
```

3. After that, you just need to import bourbon with `@import 'bourbon'`

@fourseven Maybe update `includePaths` example in `README.md` since relative path is needed for packages?

**Comment by fourseven** [comment]
Can you attempt a PR @timche? Looks like you're already done most of the hard work documenting it, I'll happily merge to the readme.

**Comment by sungwoncho** [comment]
Thanks for sharing your solution @timche. For anyone with similar problem, see [this repo](https://github.com/violetjs/violet/tree/devel/packages/theme-basic) for a real example.

**Comment by timche** [comment]
@fourseven Sure.

@sungwoncho Glad I could help.

**Comment by mmintel** [comment]
Hi there, I have the same issue and cannot fix it with the solution above.
`mquandalle:bower` is installed and the installation process went well, the files were successfully installed into `meteor/local/bower`. 

This is my bower.json in my package (also added to the package files)
```JSON
{
  "name": "mm-core",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
      "modular-scale": "2.1.1"
  }
}
```

scss.json within my package looks like this (also added to the package files)
```JSON
{
    "includePaths": [
        "../../.meteor/local/bower"
    ],
    "enableAutoprefixer": true
}
```

style.scss imports this 
```SCSS
@import 'modular-scale/stylesheets/modular-scale/_modular-scale.scss';
```

And this is the error
```BASH
=> Errors prevented startup:

   While processing files with fourseven:scss (for target web.browser):
   /packages/mmintel_mm-core/client/style.scss: Scss compiler error: File to import: modular-scale/stylesheets/modular-scale/_modular-scale.scss not found. Import origin:
   /packages/mmintel_mm-core/client/style.scss
```

**Comment by timche** [comment]
Are you sure `mquandalle:bower` is working? There is still a open (PR)[https://github.com/mquandalle/meteor-bower/pull/94].

**Comment by mmintel** [comment]
Well the files are added to /meteor/local/bower so I guess it is working.
<img width="370" alt="screen shot 2015-09-30 at 15 09 44" src="https://cloud.githubusercontent.com/assets/4574612/10193785/5285c688-6785-11e5-92f7-9618256d45b7.png">

**Comment by timche** [comment]
Have you added `scss.json` to your `package.js`?

**Comment by mmintel** [comment]
Yes!

```JS

Package.onUse(function(api) {
    api.versionsFrom('1.2.0.2');
    var dependencies = [
        'ecmascript',
        'templating',
        'angular',
        'angularui:angular-ui-router',
        'mquandalle:bower',
        'fourseven:scss'
    ];
    var packageFiles = [
        'bower.json',
        'scss.json'
    ];
    var clientFiles = [
        'client/app.js',
        'client/layout.html',
        'client/style.scss'
    ];
    api.use(dependencies);
    api.addFiles(packageFiles);
    api.addFiles(clientFiles, 'client');
});
```

**Comment by timche** [comment]
Are you on on Meteor 1.2?

Try it like this:

```js
api.addAssets([
    'scss.json'
    ], 'server');
```

**Comment by mmintel** [comment]
I am on 1.2.0.2 and these lines dont fix it, even after restarting meteor.

```JS
Package.onUse(function(api) {
    api.versionsFrom('1.2.0.2');
    var dependencies = [
        'ecmascript',
        'templating',
        'angular',
        'angularui:angular-ui-router',
        'mquandalle:bower',
        'fourseven:scss'
    ];
    var packageFiles = [
        'bower.json'
    ];
    var clientFiles = [
        'client/app.js',
        'client/layout.html',
        'client/style.scss'
    ];
    api.addAssets([
    'scss.json'
    ], 'server');
    api.use(dependencies);
    api.addFiles(packageFiles);
    api.addFiles(clientFiles, 'client');
});

**Comment by timche** [comment]
Try editing your `scss.json` like this please:

```json
{
    "includePaths": [
        "../../.meteor/local/bower/modular-scale/stylesheets/modular-scale"
    ],
    "enableAutoprefixer": true
}
```

`style.scss`

```scss
@import 'modular-scale';
```

**Comment by timche** [comment]
Nvm, it seems like your path in `style.scss` is just wrong:

Wrong
```scss
@import 'modular-scale/stylesheets/modular-scale/_modular-scale.scss';
````

Correct
```scss
@import 'modular-scale/stylesheets/_modular-scale.scss';
```

**Comment by mmintel** [comment]
Ouh you were right.. the path was wrong but the error is still there. Even when I change the include path to go down til modular-scale.

   While processing files with fourseven:scss (for target web.browser):
   /packages/mmintel_mm-core/client/style.scss: Scss compiler error: File to import: modular-scale not found. Import origin: /packages/mmintel_mm-core/client/style.scss

**Comment by sebakerckhof** [comment]
Note that the scss.json options are no longer supported in the latest version.
You'll have to stick with version 3.2.0 for now if you need these options.

**Comment by mmintel** [comment]
So there is no way to use includePaths with latest version?

**Comment by sebakerckhof** [comment]
No, in most cases it is not needed anymore, since the new version supports cross-package references. 
There were some bugs with it, but we've just pushed a fix that will be published to atmosphere soon.

I'll close this bug and track the includepath support further in #112

**Comment by derwaldgeist** [comment]
I don't understand why you removed these options and did not push the package version to a new major version?! I just updated the package, and after that my Sass files were completely broken :-( It's ok to make breaking change, but semver should be respected in this case, IMHO.

**Comment by fourseven** [comment]
Hi @derwaldgeist since this is a wrapped package (it wraps node-sass), we're not using semver, we're using node-sass's versions. There are unfortunately drawbacks here, but I think it's important to work out what sass support is possible via our package version scheme.

**Comment by derwaldgeist** [comment]
@fourseven: Thanks for that explanation. That makes pretty much sense! For now, I will stick to v3.2 and Meteor 1.1, since Meteor 1.2 introduced too many breaking changes. I'll wait until things have stabilized. The only thing I'm really missing ATM is cross-package referencing of Sass files. In v3.2, this is only possible with weird workarounds, as described in #104.
