### ISSUE TITLE
How to use index file in combination with packages?

### ISSUE THREAD

**Issue by derwaldgeist** [fourseven/meteor-scss#104]
I have two questions regarding using meteor-scss in combination with packages.

No 1.

I'm using the indexFile option to define a "main.scss" file, as described in the documentation. This results in a SCSS compiler error, since the main.scss file gets updated automatically, but pointing to a wrong location.

Sample: I've got an scss file under the following package location:
/packages/home-mobile/templates/home-mobile.scss

Based on this, the main.scss file gets automatically updated with the following path:
@import "templates/home-mobile.scss";
which is obviously not pointing to the right location.

I would expect that .scss files located in packages would be referenced with the full qualifying path, i.e. including the package's folder, in my case:
@import "packages/home-mobile/templates/home-mobile.scss";

The only "solution" I've found so far is:
* Not to reference the .scss file in the package.json to prevent it from being included in the main.scss file automatically.
* Put them in the main.scss by hand, which is quite error-prone and time-consuming - and against all loose-coupling. 

Or did I do something wrong here?

No 2.

A typical scenario is that a package would like to reference sass code located inside the main app (or in another package), for instance if you're using global sass variables or mixins. In the documentation, there is a description how this would work in combination with mquandalle:bower. In this case, the Bower files are located under .meteor/local/bower. But what can I do to reference sass files not located in a Bower package?

It would help a lot if the documentation would describe these more complex (but realistic) scenarios in combination with packages in a bit more detail. Thanks in advance for your effort.

BTW: I've also noticed that .scss files in packages are only included in the build process, if they are included with the target architecture "server", which was not what I was expecting. I (naively) thought that I could distinguish between styles for "web.browser" and "web.cordova" using the architecture flag. Strange thing is that the "architecture" flag is ignored completely by the SCSS compiler if you happen to update the file while the server is running. In this case, the SCSS file *is* considered, even if "server" has not been set as the target architecture.

**Comment by dcworldwide** [comment]
I'm also struggling with this. I want to create packages for each sass framework I'm using and have my index.scss reference them in correct load order. But I'm stuck! Anyone care to help explain / document how to do this?

**Comment by derwaldgeist** [comment]
@dcworldwide: I don't have a really good solution, since it introduces a lot of tight-coupling where there should be loose-coupling instead. But at least this workaround kinda works for me:
 * Put the ```scss``` files in the packages, but do not reference them in the ```package.js``` files. Referencing them there will add them automatically to the ```index.scss``` file, but unfortunately with a wrong reference (as explained in the original post).
 * Create a ```_packages.scss``` file in the same folder as the ```index.scss``` file.
 * Reference this file from the ```index.scss``` file, i.e. add a line
```scss
@import "packages.scss";
```
 * Add references to all packages' ```scss``` files to the ```_packages.scss``` file, using ```@import``` statements directly pointing to the respective package folder, e.g.
```scss
@import "packages/my-package/styles.scss
```
The ```packages.scss``` file is not really necessary (your could place your references right in the ```index.scss``` file instead), but it helps a lot to sort out which ```scss``` files belong to packages and which not. It also makes it a bit easier to get an overview in which order the package ```scss``` files should be loaded. Plus, it makes it easy to remove all these superfluous package ```scss``` references once the reference bug of ```fourseven:scss``` gets fixed (hopefully soon).

If you have more than one ```scss``` file per package, you can use the ```styles.scss``` file to reference these via relative links. So you only have to add one ```@import``` per package to the ```_packages.scss``` file. In fact, in my set-up the ```styles.scss``` files always contain only references to the actual ```scss``` files of the packages.

**Comment by dcworldwide** [comment]
Thanks! Will try it out

**Comment by sebakerckhof** [comment]
Closing in favor of https://github.com/fourseven/meteor-scss/issues/124

**Comment by derwaldgeist** [comment]
Is there a chance that at least the package folder reference bug in combination with the index file will be fixed? It would save me a lot of work if SCSS files in packages would be stored with valid paths, i.e. including the package folder.

**Comment by sebakerckhof** [comment]
The index file is not likely to come back in the very near future and I'm not sure what you mean with the package folder reference bug.
However, in version 3.4.0-beta1 it's possible to import from other packages or from the app itself by using the `{author:packagename}/path/to/style.scss` syntax.

**Comment by derwaldgeist** [comment]
With the package folder reference bug, I was refering to the problem stated in my initial post:
> Sample: I've got an scss file under the following package location:
/packages/home-mobile/templates/home-mobile.scss

> Based on this, the main.scss file gets automatically updated with the following path:
@import "templates/home-mobile.scss";
which is obviously not pointing to the right location.

> I would expect that .scss files located in packages would be referenced with the full qualifying path, i.e. including the package's folder, in my case:
@import "packages/home-mobile/templates/home-mobile.scss";

meaning: if you add an SCSS file to a package, the index file is updated, but with an incorrect path - which in effect breaks the build process.

**Comment by sebakerckhof** [comment]
Okay, I get what you mean now. However, this isn't easily solvable, since that's the path we receive from Meteor and there is no easy way to know the full path in Meteor 1.1 and below.
In Meteor 1.2, we could use the cross-package urls, but I'd rather not have this index file for a couple of reasons:
1) Working with packages is the best way to structure a meteor app, and you can already specify load order in the package.js file.
2) There is no easy way to know when a file has been deleted, so the index file can not be kept fully up to date.
3) For build speed, the index file is also a bad idea, since any change in any file would trigger all files to be reprocessed, which kind of eliminates the advantage of the new caching mechanism.
