### ISSUE TITLE
cssnext support

### ISSUE THREAD

**Issue by alexschomb** [fourseven/meteor-scss#105]
What is the recommended way to use [cssnext](http://cssnext.io) (includes Autoprefixer) with meteor-scss?

**Comment by fourseven** [comment]
I don't have an answer for that at the moment, I'm aware that Meteor are rethinking the asset compilation so it may come soon via them, otherwise it'd have to be a new meteor package.

**Comment by alexschomb** [comment]
Thanks for your honest answer and clarification. I'll be waiting to see what the next versions of Meteor have to offer. Closed until then.
