### ISSUE TITLE
Meteor 1.2 - cross-package imports

### ISSUE THREAD

**Issue by sebakerckhof** [fourseven/meteor-scss#106]
Hello,

Meteor 1.2 has a new plugin interface, and the default less and stylus packages allow for cross-package imports using the {packagename}/file notation.

Are there plans to add support for this?

Regards,
Seba

**Comment by fourseven** [comment]
Hi, yes, I just need to find the time to work out what's new and what needs re-coding.

**Comment by sebakerckhof** [comment]
Okay, documentation is lacking in some areas, but I tried to hack together something minimal working based of the less and stylus packages. You can find it in this fork: https://github.com/sebakerckhof/meteor-scss

What works:
SCSS compilation
Cross-package imports

What may or may not work:
Sourcemaps (I'm not sure how these are handled in meteor 1.2)

What is not included:
-Autoprefixing
-Support for any of the current options, although some of the options might not make sense with the new cross-package imports.

**Comment by sebakerckhof** [comment]
Btw, 'seems to work' means that I've tested it very quickly, with not to complex scenarios.

**Comment by fourseven** [comment]
Thanks, I've just turned it into a pull request, and will test it after work (approx 8-12 hours).

**Comment by dcworldwide** [comment]
Sounds amazing! Thanks so much for this

**Comment by fourseven** [comment]
I've merged it to master but have had problems running it on my projects – I've got a test repo here which it won't work with, it's related to scss partials and subdirectories. https://github.com/fourseven/meteor-scss-test

the error:
```
   While processing files with fourseven:scss (for target web.browser):
   client/scss/meteor-scss-test.scss:2:9: Scss compiler error: Cannot read file {}/_imports.scss for /client/scss/meteor-scss-test.scss
```

**Comment by sebakerckhof** [comment]
Yeah, seems I forgot some use cases, I'll look at it tomorrow.

**Comment by fourseven** [comment]
No problem – I've added you as a collaborator, thanks for the work you've put in so far!

**Comment by sebakerckhof** [comment]
Okay, I've got a fix ready, but I want to run some more tests to make sure I didn't forget about anything this time. I also need to do some work on better error messages.

I've also created an autoprefix compiler, but there are some limitations with the current meteor build system, see: https://github.com/meteor/meteor/issues/5219 which make it not really usable as of today. I hope to discuss this further with MDG soon.

**Comment by fourseven** [comment]
Thanks again for the work, sounds good.

That's a pain about auto-prefixer, could you link that issue in the README.md for this package as part of the updated 1.2 SCSS complier commit/PR please?

**Comment by sebakerckhof** [comment]
Okay, got some delay due to this meteor bug: https://github.com/meteor/meteor/issues/5278 . Doesn't affect this package though. 

I rewrote some parts, every use case I could think of should now work, but please verify. Changes in absolute files are not tracked by Meteor though. I believe the official less and stylus packages don't allow absolute paths, but I should also verify this.

I also removed the possibility to mark imports with *.import.scss as the SASS ways seems to be to prefix with an underscore, and one way is sufficient.

**Comment by robomatic** [comment]
I'm getting not found errors trying your fork. I'm using a package with ```api.addAssets(["path/to/_import.scss"], "server")``` then in my ```main.scss``` file in my main app ```@import "{my:package}/path/to/_import.scss"

**Comment by sebakerckhof** [comment]
That is correct, you need to add the file like this in your package.js definition:
`api.addFiles(['path/to/_import.scss'],'client',{isImport:true})`

**Comment by appinteractive** [comment]
How can I use this right now? Saw that v3.3.3 has support for this but there is no such version. And how do I add this to meteor at the moment? I'm trying to add materialize to my app and need to modify and access their variables.

**Comment by fourseven** [comment]
Hi @appinteractive - clone it down to your /packages subfolder should do it (without the .git extension) I've almost finished testing, things go well and 3.3.3 will be out soon

**Comment by robomatic** [comment]
still no luck with my tests of the cross package import... I've created a quick meteor app to help test. https://github.com/robomatic/scsstest

**Comment by robomatic** [comment]
Sorry, I was wrong, it does work. I didn't have the ```api.use('fourseven:scss')``` in the package itself. Should that be an ```api.imply```? I've updated the test sample.

**Comment by skirunman** [comment]
Any update on expected official release of 3.3.3? Thanks!

**Comment by fourseven** [comment]
Just published, thanks everyone!

**Comment by idoivri** [comment]
What if I still encounter:
`While processing files with fourseven:scss (for target web.browser):
/client/css/style.scss: Scss compiler error: File to import: .meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/packages/meteoric_ionic-sass/_ionic not found. Import origin: /client/css/style.scss`

Is it possible I have something wrong on my end?

**Comment by sebakerckhof** [comment]
meteoric ionic should be updated for the Meteor 1.2 and cross-package imports. In the meantime you can use fourseven:scss@3.2.0

**Comment by rdewolff** [comment]
Yep, using fourseven:scss@3.2.0 with ```meteor add fourseven:scss@=3.2.0``` works.

Cf. longer thread on https://github.com/meteoric/ionic-sass/issues/16.
