### ISSUE TITLE
 /* autoprefixer: off */ doen't work

### ISSUE THREAD

**Issue by emmanuelbuah** [fourseven/meteor-scss#109]
autoprefixer allows you to turn off prefixing via comments - /* autoprefixer: off */ but it doesn't work via this package.

**Comment by fourseven** [comment]
Hey, to be honest autoprefixer will be removed once meteor 1.2 is released, because their new asset processing will allow it to be a separate package.

I'm not sure whether there'll be another release for meteor 1.1 before this.

**Comment by emmanuelbuah** [comment]
Sounds good. Works for me.

**Comment by fourseven** [comment]
Closed as autoprefixer is no longer a feature of this package
