### ISSUE TITLE
Meteor 1.2 correct way to use "indexFilePath" in a package

### ISSUE THREAD

**Issue by chrslwrnc** [fourseven/meteor-scss#112]
Can someone tell me exactly how to use the scss.json file in a package? I've tried every way I can think of, but none of them are working. I had it working fine outside of a package, but for some reason it isn't working inside a package with the same logic applied.

Basically, I have app.scss in a package i've made. And I want all of the other .scss files in that same package to be added as imports.

---

Additionally, I have another package that has a "_variables.scss" file, with a lot of colour and size variables in. I want to be able to use these variables in other packages - how can I import that file? I can't seem to get this to work either.

Thanks!

**Comment by krstffr** [comment]
The scss.json file seem quite broken in 1.2, the indexFilePath don't seem to work correctly for me either after upgrading to 1.2.

**Comment by sebakerckhof** [comment]
Please read the readme

**Comment by sebakerckhof** [comment]
Closing this in favor of #124 . Cross-package imports are now possible.
