### ISSUE TITLE
Crashing on 3.3.3

### ISSUE THREAD

**Issue by pfafman** [fourseven/meteor-scss#114]
Just upgraded off of atmosphere to 3.3.3 and my app is now crashing unless I remove  this package.

Error:
```
W20150929-13:36:51.793(-7)? (STDERR) ReferenceError: Plugin is not defined
W20150929-13:36:51.793(-7)? (STDERR)     at path (caching-compiler.js:1:12)
W20150929-13:36:51.793(-7)? (STDERR)     at /Users/tep/Projects/WineSail/winesail/app/.meteor/local/build/programs/server/packages/caching-compiler.js:482:4
W20150929-13:36:51.793(-7)? (STDERR)     at multi-file-caching-compiler.js:216:2
W20150929-13:36:51.793(-7)? (STDERR)     at /Users/tep/Projects/WineSail/winesail/app/.meteor/local/build/programs/server/boot.js:242:10
W20150929-13:36:51.793(-7)? (STDERR)     at Array.forEach (native)
W20150929-13:36:51.794(-7)? (STDERR)     at Function._.each._.forEach (/Users/tep/.meteor/packages/meteor-tool/.1.1.9.r2g01y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-13:36:51.794(-7)? (STDERR)     at /Users/tep/Projects/WineSail/winesail/app/.meteor/local/build/programs/server/boot.js:137:5
```

I will take a closer look but this might be that something on your local machine did not make it into the package.

Platform:  OSX version 10.10.5 Meteor version 1.2.0.2

Forcing meteor to revert back to fourseven:scss@3.2.0 fixed the issue

**Comment by lwa** [comment]
Same for me :/

**Comment by fourseven** [comment]
Can you try cloning it into your app directly and running that? Does that crash too? Here's the instructions to run the github version - https://github.com/fourseven/meteor-scss/issues/106#issuecomment-143349468

**Comment by sebakerckhof** [comment]
I also get the error now when running locally (from repo clone)

**Comment by fourseven** [comment]
The version pinning I had to do to publish it would have broken the build. I'll see if I can change those around to get it going.

**Comment by lwa** [comment]
I am fairly new to Meteor so I don´t really know which /package subfolder is meant. There seems to be a few /package directories in my .meteor folder. Could you please provide some more information? 

Thanks!

**Comment by sebakerckhof** [comment]
Mathew meant you can create a package folder in your meteor app root
directory. Then meteor will load the package from that folder instead of
from the package server.
But I don't think it's necessary anymore

2015-09-29 23:17 GMT+02:00 lwa <notifications@github.com>:

**Comment by lwa** [comment]
Thanks sebakerckhof. So we should wait for a new release then?

**Comment by sebakerckhof** [comment]
@fourseven I wonder why you had to pin the exact versions if you also specified versionsFrom.

**Comment by sebakerckhof** [comment]
I believe the error is because you specify this line:
api.use('caching-compiler@1.0.0');

But the caching compiler isn't meant to be used this way. If you specify versionsFrom you shouldn't have to specify any other api.use than  api.use('isobuild:compiler-plugin@1.0.0');

**Comment by fourseven** [comment]
I hit this - https://github.com/meteor/meteor/issues/5244 the `caching-compiler` line is the issue, 1.0.2 won't run (`Conflict: Constraint caching-compiler@1.0.2 is not satisfied by caching-compiler 1.0.0.`) and 1.0.0 is causing the error

**Comment by sebakerckhof** [comment]
Well, it's not really clear to me why meteor requires you to specify version information if you use versionsFrom. Anyway, I think you need to specify version information directly here ` use: ['caching-compiler', 'ecmascript', 'underscore'],` in the registerBuildPlugin call.

**Comment by fourseven** [comment]
Thanks @sebakerckhof, that's fixed it. 3.3.3_1 will be out shortly.

**Comment by lwa** [comment]
Great! Thanks a lot.

**Comment by fourseven** [comment]
Can you try again with 3.3.3_1 please? It's released!

**Comment by Dweez** [comment]
I had same errors and it's ok for me now, thanks @fourseven

**Comment by sebakerckhof** [comment]
Works for me.

2015-09-30 0:09 GMT+02:00 Mathew Hartley <notifications@github.com>:

**Comment by fourseven** [comment]
No problem, sorry I published a broken release. I keep being caught out by the magic of the publish/remote-build chain.

**Comment by lwa** [comment]
works for me as well (: Thanks!
