### ISSUE TITLE
Meteor 1.2.0.2 can't import materialize.scss

### ISSUE THREAD

**Issue by sean-stanley** [fourseven/meteor-scss#116]
Hi,

I've upgraded to 3.3.3_1 and suddenly this happened when starting up my app.

```
=> Errors prevented startup:                  
   
   While processing files with fourseven:scss (for target web.browser):
   /client/index.scss: Scss compiler error: File to import: {poetic:materialize-scss}/bower_components/materialize/sass/materialize.scss not found. Import origin:
   /client/index.scss
```

I am trying to use materialize css via poetic:materialize-scss 

If I remove the new package syntax I get this error
```
=> Errors prevented startup:                  
   
   While processing files with fourseven:scss (for target web.browser):
   /client/index.scss: Scss compiler error: File to import:
   ../.meteor/local/build/programs/server/assets/packages/poetic_materialize-scss/bower_components/materialize/sass/materialize.scss not found. Import origin:
   /client/index.scss
```

This error only started when switching to meteor 1.2.0.2. I am going to go research the change log in meteor itself now so I can get back to building my app as soon as possible.

**Comment by sebakerckhof** [comment]
This is correct behavior and in line with what MDG does for less, see: https://github.com/meteor/meteor/issues/5242

Files that are intended for to be imported should be prefixed with an underscore or have the isImport flag set to true in the package.js file.

**Comment by sebakerckhof** [comment]
Suggested fix is ask the materialize package owner to change his package.
It's how the new build system works.

Temporary workaround for you might be to specify all the imports independently: https://github.com/poetic/meteor-materialize-sass/blob/master/bower_components/materialize/sass/materialize.scss

These imports all have the correct behavior.

**Comment by sebakerckhof** [comment]
Btw, If you import materialize.scss and materialize.scss is also processed by meteor, you have all the scss files twice
