### ISSUE TITLE
Empty SCSS file yields error

### ISSUE THREAD

**Issue by ffxsam** [fourseven/meteor-scss#125]
I have an empty `variables.import.scss` file and it's causing an error when I try to start up my app.

```
=> Errors prevented startup:
   
   While processing files with fourseven:scss (for target web.browser):
   /client/styles/variables.import.scss: Scss compiler error: File to read not
   found or unreadable: /Users/samh/wow/{}/client/styles/variables.import.scss
```

If I add a simple line like `$some-color: #fff;`, then the error goes away. Empty files probably shouldn't throw errors.

**Comment by sebakerckhof** [comment]
This might be a meteor bug since it also seems to happen for other compilers (e.g. stylus: https://github.com/meteor/meteor/issues/5314 )

**Comment by sebakerckhof** [comment]
Okay, this is different (but similar) to the stylus error. 
It should be fixed in the master branch, can you verify?

**Comment by fourseven** [comment]
`3.4.0-beta1` was just published which should fix this.
