### ISSUE TITLE
Support glob-style imports

### ISSUE THREAD

**Issue by sebakerckhof** [fourseven/meteor-scss#138]
I think glob imports would be a pretty powerful and useful feature to have.

Different approaches possible.
1) Wait till the importer get's a glob-like url. Then expand. However, how would we return all these files to node-sass? Concatenate them ourselves? What about sourcemaps?

2) Regex to find glob-style urls and expand them before giving it to node-sass.
This seems like the easiest method, just iterate over the allFiles map and get a list of matches and replace in the source. All other functionality of the importer stays the same.

Possible problems:
-Curly braces are used for both cross-package imports and by glob (braced sections). So how do we identify a braced section from a cross-package import.
-Using method 2: The sourcemap will probably be incorrect since we alter the source file.

**Comment by rikonor** [comment]
:+1:

**Comment by toszter** [comment]
Pardon the possible hijack, however, why am I having issues with relative imports? For example, in main.scss I @import foo/bar.scss where bar.scss contains @import _bar-one.scss and the file structure is foo/_bar-one.scss... to make it work, I have to use {} braces relative to the app root... is that intended or a bug?

**Comment by sebakerckhof** [comment]
@toszter can you try version 3.4.0-beta1 ?

**Comment by znerol** [comment]
I use the following `package.js` snipped to import all sass files available from bower components:

    Package.onUse(function (api) {
      /* ... */

      api.use('fourseven:scss');

      var path = Npm.require('path');
      var glob = Npm.require('glob');

      var options = {
        cwd: path.join(path.resolve('.'), 'packages', 'name-of-my-package'),
      };

      var files = glob.sync('bower_components/**/*.scss', options)
      api.addFiles(files, ['client'], {isImport: true});

      /* ... */
    }

**Comment by rozzzly** [comment]
@znerol wow thats sooooooo much prettier than my approach 

```
#!/usr/bin/env bash

### first half of script iterates over local packages, cd's into each


echo "======[Curating Bower Dependencies]==============================="

# not -f because this is a -dIRECTORY!
if [ -d bower_components ]; then
    echo "[Bower Dependency Indexer] Dependencies Found!"

    # ensure we've got somewhere to put the indexes, and hide errors
    mkdir indexes 2> /dev/null

    deps="bower_components"
    ##curDir=${pwd}
    cd "$deps"

    # itterate over bower_components subdirs
    for dir in $(find . -mindepth 1 -maxdepth 1 -type d); do

        dir=$(echo "$dir" | grep -Po "(?<=\.\/).*")

        echo -e "   [+] Indexing \`$dir\`..."

        # use this too often not to save as a var
        indexFile="../indexes/${dir}.json"

        # back up if theres something there
        if [ -f "$indexFile" ]; then

            # cleaning up if theres something backed up
            rm -fr "../indexes/.${dir}.json~"
            # do the backup
            echo -e "      [o] old index file found... backing up"
            mv "$indexFile" "../indexes/.${dir}.json~"
        fi

        # create file
        touch "$indexFile"

        # open json doc
        echo -e "[" >> "$indexFile"

        # list files in cur dir, grep them
        find "${PWD}/${dir}" | grep -Po "bower_components\/.*?\/_[\w-]*\.scss" | sed -e "s/^.*$/  \'&\',/" >> "$indexFile"

        # trim last comma
        #
        # https://unix.stackexchange.com/questions/162377/sed-remove-the-very-last-occurrence-of-a-string-a-comma-in-a-file
        #
        #echo "$indexFile"
        #sleep 0.500
        #cat "$indexFile" | sed -n -e x -e '$ {s/,$//;p;x;}' -e '2,$ p' > "${indexFile}2"
        #sed 's/, *$//' "$indexFile"
        # sed '/\,/,$d' "$indexFile"
        ### TODO use sed to format paths, wrap with two 's and a ,
        #
        #
        # Annnnnnnnnnnndddd... none of that works ( the trailing comma )

        # close json doc
        echo -e "]" >> "$indexFile"

    done

    # back to package's root
    cd ../
fi



```

**Comment by toszter** [comment]
@sebakerckhof --- I did and it works beautifully! Thank you for your suggestion and the fix.

**Comment by sebakerckhof** [comment]
@znerol Thanks, very useful code snippet! However, this issue is more about having glob-like imports inside scss files themselves.

**Comment by znerol** [comment]
@sebakerckhof Indeed.

However, after reading meteors `tools/isobuild/compiler-plugin.js`, I came to the conclusion that there is no clean way to add additional dependencies from within a compiler plugin. Hence, glob style imports can only be implemented in a clean way if all the import-candidates are known to meteor before the compiler plugin kicks in.

Since it is necessary to list all the SCSS files (either manually or using the glob-approach from my previous comment), IMHO glob-style imports do not add much of a benefit. You can certainly extend that approach to not only nominate library SCSS, but also your own (just leave out the `{isImport: true}` when adding them). That effectively solves the index-file use-case from previous versions without having to play tricks on meteor.

I recommend to postpone this feature request until the meteor API provides a way to add new files during a compiler pass - or maybe until 'api.addFiles' accept wildcards (MeteorCommunity/discussions#7)

**Comment by nscarcella** [comment]
Does anybody know if this feature is to be added any time soon?

**Comment by sebakerckhof** [comment]
@nscarcella It's not planned for the near future.

**Comment by nscarcella** [comment]
Bummer.

I like keeping a separate sass file for each component, but I really don't want to maintain a main file. : /

**Comment by rikonor** [comment]
@nscarcella 
You can have a non-partial sass file for each component.
For example:
```
/styles
    /utils
        _mixins.scss
        _utils.scss
        _shared.scss
    main.scss
    header.scss
    post.scss
```

`_shared.scss` imports `mixins` and `utils` and all the components import `shared`.

Notice no `main` file.
