### ISSUE TITLE
Can't include bower components bootstrap from within public folder

### ISSUE THREAD

**Issue by deusd** [fourseven/meteor-scss#139]
Hello,

After the latest 3.3.3 update I am not longer able to include bootstrap scss.  I have updated to the new style as noted in the README like so:
@import "{}/public/bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";

The file doesn't seem to be getting found however, I get this error message:
=> Errors prevented startup:
   
   While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/main.scss: Scss compiler error: File to import:
   {}/public/bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss
   not found. Import origin: /client/stylesheets/main.scss

Let me know if you need any more information, thanks!

**Comment by sebakerckhof** [comment]
Can you try version 3.4.0-beta1 ?

**Comment by deusd** [comment]
Alright I have done as instructed and all appears to be working now!  I moved my bower_components to the client dir instead of public.

Thanks!
