### ISSUE TITLE
Importing a .sass files is interpreted as .scss

### ISSUE THREAD

**Issue by thesunny** [fourseven/meteor-scss#143]
When I try to @import a partial that is a .sass file, it attempts to interpret it as a .scss file. It essentially complains that top level variables need to be terminated with a ";" (semicolon) which you do not need to do with a .sass file.

After I renamed the file to .scss and added the semicolons, everything worked fine.

**Comment by fourseven** [comment]
Hi @thesunny - this has been reported at #120 – please watch that issue for updates (bug in `node-sass`).

**Comment by thesunny** [comment]
Ack! Thanks and sorry for the dup.

**Comment by fourseven** [comment]
No problem, it's not very well labelled!
