### ISSUE TITLE
How to import files under .meteor folder?

### ISSUE THREAD

**Issue by derwaldgeist** [fourseven/meteor-scss#146]
I'm using ```mquandalle:bower``` a lot to get SASS files from frameworks that don't have an Atmosphere package yet. These bower files are always located under the .meteor folder, since this is the way ```mquandalle:bower``` handles them.

However, in the latest version of Meteor and ```fourseven:scss``` I cannot reference these files anymore. I just get an error, when I try to import from {}/.meteor/...

Is there any workaround for this? I really need these SASS files downloaded by Bower.

**Comment by sebakerckhof** [comment]
The only workaround I can think of is quite cumbersome:
Create a local package folder for all your bower components. install them using bower and add the relevant sass files to package.js of the local package.

**Comment by derwaldgeist** [comment]
You mean, I should reference from the package.js to the files located under .meteor/...? Or is there a way to load bower files in a per-package way? Is there no other way to make references to .meteor/... work again in ```fourseven:scss```?

For me, this would be a huge drawback, since my main usage of Bower was to get these SASS files... For instance, I'm using Bower to get the latest versions of the materialicons. But there's also a lot of other libraries that are only available via Bower and quite often include some SASS as well.

**Comment by sebakerckhof** [comment]
What I mean is you could just install bower components like you would do in a non-meteor project. So they just end up in a bower_components folder. However, since you probably don't want all files to be included, I recommend to do this inside a package so you can control what files are included using a package.js file.

**Comment by derwaldgeist** [comment]
Well, this way I would lose any automatic updates for these packages. Of course this would work, but it's not really a good solution. Sometimes I really hate that Meteor did re-invent the wheel by building their own packaging and build system, though I understand the reasons behind it.

**Comment by sebakerckhof** [comment]
Well, one thing that I wanted to revisit was how absolute imports (that start with a slash) work.
Currently this is absolute from the root of your filesystem, but this doesn't have much value. We could change this to the root of your app or package.

**Comment by sebakerckhof** [comment]
Can you try with this branch: https://github.com/sebakerckhof/meteor-scss/tree/absolutes 

It should work, but it will give a deprecation message, since really, the solution would be transforming bower packages into atmosphere packages (or ask project owners to also publish to atmosphere).

**Comment by derwaldgeist** [comment]
Thanks for this branch. As I've never imported a branch package before: Could I just use the version in the package.js (3.4.0-beta1), or do I have to pull the package using a git URL?

**Comment by derwaldgeist** [comment]
I've now tried out using an Atmosphere package for one of my SASS files instead, with the example of ```poetic:materialize-sass```. As it turns out, this solution is far less flexible than the Bower way I was used to before. Just a sample: The author of poetic has chosen to include the Roboto font automatically, since this is the default font for Material design. It is also including the Material Design Fonts of Materialize, which I had replaced by the community-driven MDI font instead. So am not using these fonts, but they take up unnecessary space in my app. As it is a Cordova app, I'm trying to keep the amount of unnecessary files as low as possible. With Bower, this was no problem, I could just use the ```main``` directive to decide explicitly which files I want. For Atmosphere packages, it is just "take it or leave it". No offense to you, but I really think the whole Meteor packaging system, as it works now, is somewhat "broken by design". I tried to workaround these limitations by using Bower, but now I'm literally forced to do it the Meteor way. Which requires a lot of workaround and might even cause side-effects due to double code.

**Comment by sebakerckhof** [comment]
> do I have to pull the package using a git URL?

Yes, clone the repo into the packages folder of your application

>  Do you happen to know where package files are downloaded exactly?

On linux (and probably also on mac) it's `~/.meteor/packages/`
On Windows: `%appdata%\..\Local\.meteor\packages\`

> So an absolute syntax like /.meteor/... would be possible

Well the branch I made will scan for `.meteor` at the beginning of the url (so leave out the first `/`). It will give you a bit too much deprecation messages for now, but I'll fix that.

**Comment by stinghz** [comment]
Hello,    I'm trying to get @import "compass/typography";       working.
I still get below error after cloning and applying the package:

   While processing files with fourseven:scss-1 (for target web.browser):
   /client/theme-kingadmin/sass/main.scss: Scss compiler error: File to import: {}/client/theme-kingadmin/sass/partials/compass/typography
   not found in file: partials/base

**Comment by sebakerckhof** [comment]
Compass doesn't work with libsass (which this library uses), but only in
ruby-sass (which is less and less used).

2015-10-26 0:35 GMT+01:00 stinghz <notifications@github.com>:

**Comment by stinghz** [comment]
@sebakerckhof ,  thank you for the reply!  @import "compass/typography";  was working before I upgrade to Meteor 1.2,  can you think of an option for me to fix this issue?  Much appreciated

**Comment by stinghz** [comment]
francocatena:compass  this is package I used for compass

**Comment by stinghz** [comment]
Just found out the solution : 
use 
@import "{francocatena:compass}/compass/typography";
instead of 
@import "compass/typography";

**Comment by sebakerckhof** [comment]
Closing, since this is outdated for Meteor 1.3+
