### ISSUE TITLE
What happened to scss.json and load order?

### ISSUE THREAD

**Issue by satyavh** [fourseven/meteor-scss#148]
Hi,

Imo, this was the killer feature of this package. Where did it go?

**Comment by sebakerckhof** [comment]
It's gone since it doesn't play well together with the new meteor build system. You can still use version 3.2.0 if you really need it.

**Comment by satyavh** [comment]
That's too bad. Is there any way to control load order using the new build system?

**Comment by sebakerckhof** [comment]
If you work package based, then of course you  have the package.js file to control load order.
If you don't work package based you can mark your scss files as partials (by prefixing them with an underscore) and have a scss file where you import them in the order you want.

**Comment by satyavh** [comment]
Ok clear, thanks for the help. Closing this now.

**Comment by patrickml** [comment]
If its gone how do we autoprefix?

**Comment by sebakerckhof** [comment]
@patrickml We've decided to put autoprefixer in the minifier stage, where it's better fit (although not perfect, but as good as it gets right now): https://atmospherejs.com/seba/minifiers-autoprefixer

**Comment by jkhoffman** [comment]
What is the *actual* load order in the newest version?

In the meteor documentation, it says files in lib/ are loaded first. I put my main imports there (in styles.scss), but they're still being loaded too late, still. Is FourSeven's load order just depth-based?

I'm using Meteor 1.2.1 and FourSeven SCSS 3.4.1.

**Comment by sebakerckhof** [comment]
Load order is still the same as with normal meteor files. 
Except import files (prefixed by _) will not be loaded automatically, but only at the location they are imported by sass.
