### ISSUE TITLE
node-sass 3.4.1 is ready

### ISSUE THREAD

**Issue by juliancwirko** [fourseven/meteor-scss#151]
Just wanted to say that there is node-sass 3.4.1 https://github.com/sass/node-sass/releases there is no need for beta version now.

...also remember to create new release here on GitHub ;) I watch it from outside ;) Thanks!

**Comment by NicolasParada** [comment]
I wonder if the problem with the old sass indented syntax [sass/node-sass#1192](https://github.com/sass/node-sass/issues/1192) was solved... The issue is still open :S

**Comment by sebakerckhof** [comment]
Well, in fact the bug is in the c++ library (libsass) and not in node-sass,
so I guess we'll have to wait a bit longer :(.

2015-10-26 4:19 GMT+01:00 Nicolás Parada <notifications@github.com>:

**Comment by NicolasParada** [comment]
:(

**Comment by juliancwirko** [comment]
In fact we need a quick update because of some regressions in libsass 3.4.0 We should have node-sass 3.4.1 here 
for example: https://github.com/sass/libsass/issues/1624

**Comment by juliancwirko** [comment]
Ok it is updated. Many thanks!
