### ISSUE TITLE
No compatible binary

### ISSUE THREAD

**Issue by NicolasParada** [fourseven/meteor-scss#155]
```
 => Errors while adding packages:

While checking for fourseven:scss@3.4.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```
On windows 10. Meteor version 1.2.1

**Comment by juliancwirko** [comment]
@fourseven `meteor publish-for-arch` is needed here?

**Comment by NicolasParada** [comment]
Nevermind. It worked after a couple of tries... because of yes.

**Comment by sebakerckhof** [comment]
Okay, closing, you were probably just trying in the timeframe the binaries were building.

**Comment by NicolasParada** [comment]
Ok.

**Comment by fourseven** [comment]
Sorry yes, it took a few tries to build on most of the boxes – 3/4 of them restarted while it was building and the OS X box didn't actually have meteor installed on it. Fun times!
