### ISSUE TITLE
Segmentation fault ('Core' generated) when bad indentation

### ISSUE THREAD

**Issue by jc2** [fourseven/meteor-scss#158]
SO: Fedora 22 KDE
Meteor 1.2.1
Fourseven:scss 3.4.1

File type: Sass

Error:
When the sass code is not well indented, when i try to run meteor the next message appears:
Segmentation fault ('Core' generated)

**Comment by sebakerckhof** [comment]
duplicate of https://github.com/fourseven/meteor-scss/issues/120
