### ISSUE TITLE
How to generate more than one pipeline?

### ISSUE THREAD

**Issue by squallstar** [fourseven/meteor-scss#159]
Hello,

I'm currently generating some server-side pages with Meteor (with the SSR package) and I'd like to know if there's a way to generate a second pipeline for the SCSS files, so I can use one for the server-side stuff.

Basically, on top of the Meteor application I am outputting some static pages with server-side iron-router routes and would like to know either how to reference the generated css file or a new one coming from a parallel pipeline.

e.g.
- *1st pipeline*: collects scss files and appends css link to body for clients (done automatically)
- *2nd pipeline*: collects some other scss files and generate a public css asset, which will be references (not sure how)

Is there a way to achieve this with the current library?

Thanks

**Comment by sebakerckhof** [comment]
We currently do not support this and have no near-term plans for doing so. Therefore I'll close this issue. This might change depending on how the meteor build tool evolves, which is undergoing changes for 1.3

**Comment by squallstar** [comment]
So sad; I had to switch to an external build tool (grunt) to generate more pipelines and release them in the `public` folder after build.
