### ISSUE TITLE
Dynamic import of compiled partials

### ISSUE THREAD

**Issue by donwojtallo** [fourseven/meteor-scss#160]
I'm trying to add themes to my Meteor app. I want to have code like this (pseudocode):
```
// server startup
var compiler = new SassCompiler();
compiler.compile('light-theme', '_light.scss');
compiler.compile('dark-theme', '_dark.scss');

//on client wants new theme
Meteor.methods({
  'getTheme': function(themeName) {
    compiler.getUrlForTheme(themeName);
  }
});
```
Can I achieve that using this package?

**Comment by sebakerckhof** [comment]
Not at this moment due to the way the Meteor build pipeline works.
In the end all css files are concatenated. Having separate files would require changes to Meteor. It's quite likely the Meteor build pipeline will change in the future, but not by tomorrow.

**Comment by donwojtallo** [comment]
Thank You for explanation.
I already solved my problem in a slightly different way:
```
@mixin generate-theme(
	$theme-class,
	$bg-color,
	$text-color
) {

	body.#{$theme-class}-theme {
		// general
		background-color: $bg-color;
		color: $text-color;
	}
}

// Light theme
@include generate-theme(
	'material-light',	// theme class
	white,	// bg-color
	rgba(0, 0, 0, 0.870588),	// text-color
);
// Dark theme
@include generate-theme(
	'material-dark',	// theme class
	#303030,	// bg-color
	rgba(255, 255, 255, 0.870588),	// text-color
);
```
All themes all merged into one CSS, which is obvious. But it works.
