### ISSUE TITLE
No compatible binary

### ISSUE THREAD

**Issue by scipio314** [fourseven/meteor-scss#161]
=> Errors while adding packages:

    While checking for fourseven:scss@3.4.1:
    error: No compatible binary build found for this package. Contact the package author 
    and ask them to publish it for your platform.

Using raspberry pi 2 Jessie, meteor 1.2.1

**Comment by fourseven** [comment]
Sorry @scipio314 – ARM [isn't supported by Meteor](https://github.com/meteor/meteor/pull/2707) so there aren't build boxes for us to make binary packages for that platform. I'm not entirely sure how to cross-compile it either.

Officially, we can't support it. Are their easy ways to emulate a raspberry pi?

**Comment by scipio314** [comment]
I was able to run meteor using this repo here: https://github.com/4commerce-technologies-AG/meteor

**Comment by fourseven** [comment]
Can you please try cloning this repo into your project's `packages` subfolder (remove the .git extension when you clone it) - that will allow it to run locally and not from the (non-existant) binary package manager.

**Comment by scipio314** [comment]
How do I clone to a folder that is not empty?

**Comment by mkools** [comment]
I get the same error under FreeBSD 10.2, any idea how to fix?

While checking for fourseven:scss@3.4.1:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

I did try scipio314's link for meteor, same error.

**Comment by fourseven** [comment]
FreeBSD isn't supported by meteor so there's no tooling to build binary packages for it (which is what this package is). Your best option is trying to run it as a git clone, so clone down this package into your project's `/packages` subfolder and meteor should recognise and build it from there, instead of trying to get something which doesn't exist.

**Comment by mkools** [comment]
Awesome I'll try that thanks for the prompt reply.

**Comment by mkools** [comment]
That did the job, thanks guys!

**Comment by LeG3nDz** [comment]
Hi every body,

I've try to clone this repo on .meteor/packages but when i start meteor, my scss not compile.

Do you have any idea ?

**Comment by sebakerckhof** [comment]
shouldn't be on .meteor/packages, on the root level of your app (so on same level as .meteor)

**Comment by LeG3nDz** [comment]
Wo, sorry :)

But, after Meteor add, i've this error :

`
compileScssBatch: updating npm dependencies -- node-sass...
 => Errors while adding packages:

While building plugin `compileScssBatch` in package `fourseven:scss`:
error: couldn't install npm package node-sass@3.4.2: Command failed: npm WARN
deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now
out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a
build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on
node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.
Use 'npm ls graceful-fs' to find it in the tree.

module.js:340
throw err;
^
Error: Cannot find module
'/root/meteor/app.stephane-richin.lan/packages/meteor-scss/.npm/plugin/compileScssBatch-new-1vc21zz/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:935:3
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.9-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/lib/meteor/dev_bundle/bin/npm"
"install" "node-sass@3.4.2"
npm ERR! cwd
/root/meteor/app.stephane-richin.lan/packages/meteor-scss/.npm/plugin/compileScssBatch-new-1vc21zz
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a
build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on
node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.
Use 'npm ls graceful-fs' to find it in the tree.

module.js:340
throw err;
^
Error: Cannot find module
'/root/meteor/app.stephane-richin.lan/packages/meteor-scss/.npm/plugin/compileScssBatch-new-1vc21zz/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:935:3
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.9-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/lib/meteor/dev_bundle/bin/npm"
"install" "node-sass@3.4.2"
npm ERR! cwd
/root/meteor/app.stephane-richin.lan/packages/meteor-scss/.npm/plugin/compileScssBatch-new-1vc21zz
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
`

Do you have any idea ?

Thank you,

**Comment by vinaynb** [comment]
@mkools hey can you guide me a little as to where did you clone this project inside the meteor app ? i tried cloning it at the same level as @sebakerckhof suggested but after cloning i ran meteor add command again and it failed to find a binary and shows the same error 'no binary found for this platform'.
