### ISSUE TITLE
Full scss.json documentation

### ISSUE THREAD

**Issue by thatgibbyguy** [fourseven/meteor-scss#166]
Great work on this package by the way!

I've so far been able to use fourseven/meteor-scss with very few issues, but when trying to explain scss.json to peers I'm unable to do so fully because I can't find any complete documentation on it - rather I only find comments on this repo about it.

Does this documentation exist? If so could you provide it?

**Comment by sebakerckhof** [comment]
Closing since `scss.json` is no longer supported in newer versions
