### ISSUE TITLE
Package won't update

### ISSUE THREAD

**Issue by chackerian** [fourseven/meteor-scss#169]
For a long period of time I have tried to update this package with **sudo meteor update** and **sudo meteor update fourseven:scss** but it remains at the same version.

**meteor list** prompts

Newer versions of the following indirect dependencies are available:
 * fourseven:scss 1.2.3 (3.4.1 is available)

When I run **sudo meteor update fourseven:scss**

It returns 

The specified packages are at their latest compatible versions.

Anyone have any ideas for scss stuck at 1.2.3?

**Comment by sebakerckhof** [comment]
Which meteor version does your project use?

**Comment by chackerian** [comment]
The latest version `Meteor 1.2.1`

**Comment by chackerian** [comment]
I have matthew:foundation5-sass installed, I don't know if this is causing issues

**Comment by sebakerckhof** [comment]
@chackerian I haven't been able to reproduce and there are no other reports of this. Have you been able to fix it?

What you could try to do is set the version manually in your .meteor/versions file. If there is another package which conflicts, Meteor should tell you which package is causing the problem.
