### ISSUE TITLE
seba:minifiers-autoprefixer vs standard-minifiers

### ISSUE THREAD

**Issue by vuhrmeister** [fourseven/meteor-scss#170]
Why should I use `seba:minifiers-autoprefixer` over `standard-minifiers`?

What's the difference or the benefits? `seba:minifiers-autoprefixer` does not seam to be widely used and I would rather like to stay with the official package.

**Comment by sebakerckhof** [comment]
Well, It has css autoprefixing. Standard minifiers not.

**Comment by vuhrmeister** [comment]
I'm just a bit confused, because I'm currently updating this package from `3.2.0` to `3.4.1`. And in `3.2.0` Autoprefixer is included. So this is the whole point I guess?

May I ask another question regarding the upgrade?
- The scss.json config file is now obsolete?
- Auto including files into the index file is not supported anymore? So I need to do it manually now?

**Comment by sebakerckhof** [comment]
Yes. Due to changes in the Meteor build tool in 1.2, we had to do things differently. This meant throwing out some features and doing it more in the meteor way. It does give you cross package imports in return.
