### ISSUE TITLE
Document that `imports/` directory in Meteor 1.3 makes something an "import"

### ISSUE THREAD

**Issue by stubailo** [fourseven/meteor-scss#172]
Right now, this section: https://github.com/fourseven/meteor-scss/#file-types doesn't cover that putting a file in `imports/` also makes it not load eagerly. Probably worth updating now that 1.3 is out.

**Comment by sebakerckhof** [comment]
Closing per https://github.com/fourseven/meteor-scss/commit/7189df6c37f9779a1795de68c2b8868216b52802
