### ISSUE TITLE
Cant get this to compile my scss files

### ISSUE THREAD

**Issue by deanp70** [fourseven/meteor-scss#176]
I went through the installation process, and when I activate meteor, I lose all my css styling.

the project runs correctly, but no style.

would love some help.
thanks!

**Comment by sebakerckhof** [comment]
Can you create a repo with a reproduction.

**Comment by deanp70** [comment]
hey!
thanks for the quick reply. I tried working on it today and solved the problem, it was another add-on that messed it up when combined with this one.

thanks again!
Dean
