### ISSUE TITLE
Conflict with Meteor 1.3.2.x

### ISSUE THREAD

**Issue by pors** [fourseven/meteor-scss#177]
It is unclear if this is a Meteor or meteor-scss issue, but updating to Meteor 1.3.2.2 or 1.3.2.4 results in this error:

```
/Users/mark/.meteor/packages/fourseven_scss/.3.4.3.ifmf9n++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;

TypeError: Cannot call method 'substr' of undefined
```

See also https://github.com/meteor/meteor/issues/6851

**Comment by cyclops24** [comment]
I think it's Meteor build error. Maybe related [this issue](https://github.com/meteor/meteor/issues/5920) that reported by me later.
I fixed my issue with remove all comments from my codes. Read above issue for more info.

**Comment by pors** [comment]
@cyclops24 I think it is unrelated. When I remove fourseven:scss from my app it builds fine (but I don't have any css working in my app of course).

**Comment by JanMP** [comment]
I have the same problem with stylus and Meteor 1.3.2.4

**Comment by MasterAM** [comment]
Happened to me with `less`. 
After I removed a `.less` file import from withing a `.jsx` file, everything was built properly.

Did you guys import `scss` from `js`?

**Comment by pors** [comment]
@MasterAM yes I did import scss from js, because my library needs to work both with meteor and with webpack (withouth Meteor). Previous versions of Meteor ignored these imports apparently, but 1.3.2.2+ chokes on it.

I resolved it by moving the "require" into a file outside of the Meteor app directory, see https://github.com/reactionic/reactionic-kitchensink/commit/7fd730bba868f9b012ff321fb7a7976af3b4659f
