### ISSUE TITLE
Line numbers missing from error messages

### ISSUE THREAD

**Issue by teetow** [fourseven/meteor-scss#185]
While processing files with fourseven:scss (for target web.browser):
    /client/foobar.scss: Scss compiler error: error reading values after (

With LESS, I get line numbers in my error messages. With this package, I don't. Would be kinda nice to have them.

**Comment by sebakerckhof** [comment]
Yeah, the less compiler gives this information. 
Node-sass, which does the actual compilation, doesn't give me this info, so I can't fix this...
