### ISSUE TITLE
SCSS does work, but there's no compiled CSS file anywhere in the app directory

### ISSUE THREAD

**Issue by pashinsky** [fourseven/meteor-scss#186]
Hi,

I'm not sure exactly how this intended to work, and I'm confused a bit. I can see that Meteor does use the plugin (for example, there're errors in Meteor server logs when there're errors in syntax in SCSS file), and moreover, changes appear when server refreshes, but there's no compiled CSS file for some reason.

When I inspect the element for which I wrote some SCSS, it says that the element uses the following stylesheet: '/merged-stylesheets-prefixed.css?hash=…'

![scss](https://cloud.githubusercontent.com/assets/3601251/16364523/3c50cd8c-3bfa-11e6-8cfb-b87d5160ec7d.png)

But there's no actual file in my app folder. Does this work as intended? 

Thanks!

**Comment by sebakerckhof** [comment]
I'm not sure if I understand the question correct.
The `merged-stylesheets-prefixed.css` file is served from the `.meteor\local\build\programs\web.browser` directory of your application (in dev mode).

**Comment by pashinsky** [comment]
Thanks Seba, now I see it! I just got used to a quite different way of compiling SCSS with Codekit. But that's OK.
