### ISSUE TITLE
Can it compile SASS located in node_modules?

### ISSUE THREAD

**Issue by PolGuixe** [fourseven/meteor-scss#195]
I have installed [React-Toolbox](http://react-toolbox.com/#/install), that needs to: 

> compile and require SASS files located in your `node_modules`

I am trying to use this package, however I doesn't seem to work.

**Comment by englishtom** [comment]
I had the same requirement wanting to import Foundation 6 from node_modules. I created a main.scss file in /client/styles and used the following to import from node_modules:

`@import '../../node_modules/foundation-sites/scss/foundation.scss';`

**Comment by PolGuixe** [comment]
I have finally used https://github.com/nathantreid/meteor-css-modules

**Comment by sebakerckhof** [comment]
Let's continue the discussion here: https://github.com/fourseven/meteor-scss/issues/165
