### ISSUE TITLE
application.scss: Scss compiler error: fs.existsSync is not a function

### ISSUE THREAD

**Issue by stewiegaribaldi** [fourseven/meteor-scss#198]
Does anyone experience this?

it seems because of the latest node (my versions is 4.4.7) has deprecated fs.existsSync but meteor-scss fileExists should automatically use fs.accessSync, shouldn't it?

Thank you!

**Comment by hthannah34** [comment]
+1

**Comment by tparkin** [comment]
+1

**Comment by mitar** [comment]
This was resolved in #200.
