### ISSUE TITLE
Broken on Meteor 1.4

### ISSUE THREAD

**Issue by zorrobyte** [fourseven/meteor-scss#199]
Mac15:foundation rossfisher$ meteor add zurb:foundation-sites
 => Errors while adding packages:                                               
                                              
While downloading fourseven:scss@3.4.3...:
error: Command failed:
/Users/rossfisher/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/private/var/folders/j5/g23dlhfx22s7l74dgbz0hl2r0000gn/T/mt-1a4qw5v/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-f8wml5/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/rossfisher/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/rossfisher/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/private/var/folders/j5/g23dlhfx22s7l74dgbz0hl2r0000gn/T/mt-1a4qw5v/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-f8wml5/npm-debug.log
module.js:327
throw err;
^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous>
(/private/var/folders/j5/g23dlhfx22s7l74dgbz0hl2r0000gn/T/mt-1a4qw5v/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-f8wml5/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/rossfisher/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/rossfisher/.meteor/packages/meteor-tool/.1.4.0-1.l0olq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/private/var/folders/j5/g23dlhfx22s7l74dgbz0hl2r0000gn/T/mt-1a4qw5v/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-f8wml5/npm-debug.log

**Comment by h2m2** [comment]
thanks to all opening this one. 
I just removed the fourseven package 
Did not help. It installs, and installs and installs.  There is no trace of it .... looks like some other package
dictates that. But it stops everything, cause you cannot remove it.
And always fails.... no 1.4.0.1  cool 
yet another full sack with meteor

**Comment by h2m2** [comment]
the fourseven package loads "out of nowhere".. even in 1.3.5. 
it is like a pest, you cannot get rid of it - no installing later... no. Top priority: kill the plattform. Super.
Everything is dead. Every version.



PS C:\Users\H2M2\myapp> meteor --release 1.3.5
=> Using Meteor 1.3.5 as requested (overriding Meteor 1.3.4)

[[[[[ C:\Users\H2M2\myapp ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package fourseven:scss@3.3.3_3:
   error: Command failed: gyp info it worked if it ends with ok
   gyp verb cli [ 'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
   gyp verb cli
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.0.3
   gyp info using node@0.10.45 | win32 | ia32
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp verb check python checking for Python executable "C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe" in
   the PATH
   gyp verb `which` succeeded C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe
   C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe
   gyp verb check python version `C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe -c "import platform;
   print(platform.python_version());"` returned: "2.7.10\r\n"
   gyp verb get node dir no --target version specified, falling back to host node version: 0.10.45
   gyp verb command install [ '0.10.45' ]
   gyp verb install input version string "0.10.45"
   gyp verb install installing version: 0.10.45
   gyp verb install --ensure was passed, so won't reinstall if already installed
   gyp verb install version is already installed, need to check "installVersion"
   gyp verb got "installVersion" 9
   gyp verb needs "installVersion" 9
   gyp verb install version is good
   gyp verb get node dir target node version installed: 0.10.45
   gyp verb build dir attempting to create "build" dir:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\build
   gyp verb build dir "build" dir needed to be created?
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\build
   gyp verb build/config.gypi creating config file
   gyp verb build/config.gypi writing out config file:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\build\config.gypi
   gyp verb config.gypi checking for gypi file:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\config.gypi
   gyp verb common.gypi checking for gypi file:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\common.gypi
   gyp verb gyp gyp format was not specified; forcing "msvs"
   gyp info spawn C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe
   gyp info spawn args [
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp\\gyp\\gyp_main.py',
   gyp info spawn args   'binding.gyp',
   gyp info spawn args   '-f',
   gyp info spawn args   'msvs',
   gyp info spawn args   '-G',
   gyp info spawn args   'msvs_version=auto',
   gyp info spawn args   '-I',
   gyp info spawn args
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\build\\config.gypi',
   gyp info spawn args   '-I',
   gyp info spawn args
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp\\addon.gypi',
   gyp info spawn args   '-I',
   gyp info spawn args   'C:\\Users\\H2M2\\.node-gyp\\0.10.45\\include\\node\\common.gypi',
   gyp info spawn args   '-Dlibrary=shared_library',
   gyp info spawn args   '-Dvisibility=default',
   gyp info spawn args   '-Dnode_root_dir=C:\\Users\\H2M2\\.node-gyp\\0.10.45',
   gyp info spawn args
   '-Dnode_gyp_dir=C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBa
tch\\compileScssBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp',
   gyp info spawn args   '-Dnode_lib_file=node.lib',
   gyp info spawn args
   '-Dmodule_root_dir=C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScs
sBatch\\compileScssBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass',
   gyp info spawn args   '--depth=.',
   gyp info spawn args   '--no-parallel',
   gyp info spawn args   '--generator-output',
   gyp info spawn args
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\build',
   gyp info spawn args   '-Goutput_dir=.' ]
   Traceback (most recent call last):
   File
   "C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mo
dules\.temp-18joc9u\node_modules\node-sass\node_modules\node-gyp\gyp\gyp_main.py",
   line 15, in <module>
   import gyp
   ImportError: No module named gyp
   gypBuild failed

   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv "C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.5\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.5\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild"
   "--no-bin-links" "--update-binary"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/build.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.

   gyp info it worked if it ends with ok
   gyp verb cli [ 'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.4\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
   gyp verb cli
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.0.3
   gyp info using node@0.10.45 | win32 | ia32
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp verb check python checking for Python executable "C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe" in
   the PATH
   gyp verb `which` succeeded C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe
   C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe
   gyp verb check python version `C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe -c "import platform;
   print(platform.python_version());"` returned: "2.7.10\r\n"
   gyp verb get node dir no --target version specified, falling back to host node version: 0.10.45
   gyp verb command install [ '0.10.45' ]
   gyp verb install input version string "0.10.45"
   gyp verb install installing version: 0.10.45
   gyp verb install --ensure was passed, so won't reinstall if already installed
   gyp verb install version is already installed, need to check "installVersion"
   gyp verb got "installVersion" 9
   gyp verb needs "installVersion" 9
   gyp verb install version is good
   gyp verb get node dir target node version installed: 0.10.45
   gyp verb build dir attempting to create "build" dir:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\build
   gyp verb build dir "build" dir needed to be created?
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\build
   gyp verb build/config.gypi creating config file
   gyp verb build/config.gypi writing out config file:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\build\config.gypi
   gyp verb config.gypi checking for gypi file:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\config.gypi
   gyp verb common.gypi checking for gypi file:
   C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mod
ules\.temp-18joc9u\node_modules\node-sass\common.gypi
   gyp verb gyp gyp format was not specified; forcing "msvs"
   gyp info spawn C:\Users\H2M2\AppData\Local\.meteor\packages\meteor-tool\1.3.4\mt-os.windows.x86_32\dev_bundle\python\python.exe
   gyp info spawn args [
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp\\gyp\\gyp_main.py',
   gyp info spawn args   'binding.gyp',
   gyp info spawn args   '-f',
   gyp info spawn args   'msvs',
   gyp info spawn args   '-G',
   gyp info spawn args   'msvs_version=auto',
   gyp info spawn args   '-I',
   gyp info spawn args
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\build\\config.gypi',
   gyp info spawn args   '-I',
   gyp info spawn args
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp\\addon.gypi',
   gyp info spawn args   '-I',
   gyp info spawn args   'C:\\Users\\H2M2\\.node-gyp\\0.10.45\\include\\node\\common.gypi',
   gyp info spawn args   '-Dlibrary=shared_library',
   gyp info spawn args   '-Dvisibility=default',
   gyp info spawn args   '-Dnode_root_dir=C:\\Users\\H2M2\\.node-gyp\\0.10.45',
   gyp info spawn args
   '-Dnode_gyp_dir=C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBa
tch\\compileScssBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\node_modules\\node-gyp',
   gyp info spawn args   '-Dnode_lib_file=node.lib',
   gyp info spawn args
   '-Dmodule_root_dir=C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScs
sBatch\\compileScssBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass',
   gyp info spawn args   '--depth=.',
   gyp info spawn args   '--no-parallel',
   gyp info spawn args   '--generator-output',
   gyp info spawn args
   'C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.3.3_3\\plugin.compileScssBatch.os.windows.x86_32\\npm\\node_modules\\meteor\\compileScssBatch\\compileScs
sBatch\\node_modules\\.temp-18joc9u\\node_modules\\node-sass\\build',
   gyp info spawn args   '-Goutput_dir=.' ]
   Traceback (most recent call last):
   File
   "C:\Users\H2M2\AppData\Local\.meteor\packages\fourseven_scss\3.3.3_3\plugin.compileScssBatch.os.windows.x86_32\npm\node_modules\meteor\compileScssBatch\compileScssBatch\node_mo
dules\.temp-18joc9u\node_modules\node-sass\node_modules\node-gyp\gyp\gyp_main.py",
   line 15, in <module>
   import gyp
   ImportError: No module named gyp
   gypBuild failed

   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv "C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.5\\mt-os.windows.x86_32\\dev_bundle\\bin\\\\node.exe"
   "C:\\Users\\H2M2\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.3.5\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild"
   "--no-bin-links" "--update-binary"
   npm ERR! node v0.10.46
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.3.3 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the node-sass@3.3.3 postinstall script 'node scripts/build.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/build.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.



=> Your application has errors. Waiting for file change.

**Comment by richardgsands** [comment]
+1

**Comment by mitar** [comment]
I am not sure what is this issue about? With Meteor 1.3.2+ you should be using 3.8.0 or newer version of this package. You are trying to use 3.4.3 with Meteor 1.4 so it fails.

**Comment by mitar** [comment]
(You can just change the version in `.meteor/versions` to the latest package version to force it to use it.)

**Comment by zorrobyte** [comment]
Thank you @mitar - I'll put in a PR to update the version of meteor-scss the foundation guys are using, as this all started with "meteor add zurb:foundation-sites"
