### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by sturoid** [fourseven/meteor-scss#206]
I upgraded to Meteor 1.4.1 and set fourseven:scss@=3.8.1  in packages. Everything works locally, but when I try and deploy to Heroku I get the following error:

```
=> Errors while initializing project:
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

I'm using meteor-buildpack-horse on Heroku. Everything workes great on Meteor 1.3.5.1. Any help would be much appreciated.

**Comment by sebakerckhof** [comment]
Duplicate of: https://github.com/fourseven/meteor-scss/issues/201#issuecomment-238406807
