### ISSUE TITLE
Cannot publish to Heroku with meteor-scss version 3.8.1 

### ISSUE THREAD

**Issue by manooh** [fourseven/meteor-scss#207]
I just tried to push my new app to Heroku, got the following error:
`=> Errors while initializing project:
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.`

Downgrading to version 3.8.0_1 fixed the problem.

**Comment by dorseth** [comment]
Also can confirm that, got the same error while installing the package.

**Comment by ziedmahdi** [comment]
related to this issue #210

**Comment by sebakerckhof** [comment]
Duplicate of https://github.com/fourseven/meteor-scss/issues/201
