### ISSUE TITLE
ARM Architecture

### ISSUE THREAD

**Issue by tylershuster** [fourseven/meteor-scss#209]
I'm running a project on a Raspberry Pi. I'm aware that `node-sass` and `phantomjs` don't support ARM so I build them myself (verified when I used another project on which they relied). However my Meteor project using `meteor-scss` fails due to `No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.`

Could you give me a hand?

**Comment by sebakerckhof** [comment]
See discussion here: https://github.com/fourseven/meteor-scss/issues/161

**Comment by sebakerckhof** [comment]
Starting from meteor 1.4.1, this problem should be solved since packages can then recompile themselves automatically on the host platform.
