### ISSUE TITLE
No binary builds for [3.8.1]

### ISSUE THREAD

**Issue by derencel20** [fourseven/meteor-scss#210]
I can't seem to add it using `meteor add fourseven:scss`. It says no binary builds.

**Comment by aaandreyev** [comment]
same here, what's the deal?

**Comment by ziedmahdi** [comment]
@fourseven I think when you published the 3.8.1 atmospherejs was down (or having some problems). You may have to create 3.8.2 version and publish it again to solve this error.

@derencel20, @aaandreyev you may want to clone this repo in your /packages folder as a workaround

**Comment by sebakerckhof** [comment]
Duplicate of: https://github.com/fourseven/meteor-scss/issues/201
