### ISSUE TITLE
Autoprefixing on Imported file

### ISSUE THREAD

**Issue by bduff9** [fourseven/meteor-scss#213]
Hi there, I recently noticed something and I'm not sure if I'm doing something wrong or am missing some config.

I have a meteor app using react.  On each page, I import a scss file for that page's styles, like `import './SomeComponent.scss';`  While this works, it doesn't seem to add any sort of prefixing, giving me issues on certain browsers.

I have both fourseven and postcss installed, and my postcss has this in package.json:
`"postcss": {
    "plugins": {
      "autoprefixer": {
        "browsers": [
          "last 2 versions",
          "ie >= 9",
          "and_chr >= 2.3"
        ]
      }
    }
  }`

Any thoughts on what I can do to get this to work?  Thanks!

**Comment by sebakerckhof** [comment]
This should be asked at the postcss plugin repo.
Anyway, postcss runs in the minification step of the build tool, so I'm not sure if that runs when importing scss like you do.

**Comment by bduff9** [comment]
OK but before you close it, can you suggest an alternative that will work with your package?  I looked over at the postcss and apparently this issue has been reported, however in this package here you say that all scss files could be processed from the imports folder.  If the scss were compiled into css properly with autoprefixing, I could also just import the css file into my component.  However, there are no generated css files anywhere I can see.  I assume since your docs say this should work, it is something you would help with:
"Without any additional configuration after installation, this package automatically finds all .scss and .sass files in your project, compiles them with node-sass, and includes the resulting CSS in the application bundle that Meteor sends to the client."

"Each compiled source file produces a separate CSS file. (The standard-minifiers package merges them into one file afterwards.)"

Would you mind taking a look as I would love not to have to rewrite every single component to pull styles from one master file.

**Comment by sebakerckhof** [comment]
Well, basically the only thing this plugin does is: it receives scss files from meteor, it processes them and passes them back to meteor. In the normal way, meteor will save the output css to files somewhere in the app build (under .meteor/local during development). However, if you import scss in your javascript files, Meteor will not save them as files, but it puts them directly in the HTML. This means they do not get processed by the minifier and so you don't get autoprefixing. I don't know of a way to make autoprefixing work with those kind of imports.
