### ISSUE TITLE
Meteor 1.4.1 update

### ISSUE THREAD

**Issue by skemb321** [fourseven/meteor-scss#214]
Please make this work for 1.4.1 :(

Thanks

**Comment by mitar** [comment]
Hm, for me it works locally, but on the clean installation I get the following error:

```
While checking for fourseven:scss@3.8.1:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

Is this what does not work for you as well?

**Comment by mitar** [comment]
It seems this is related to #215.

Otherwise it works for me with Meteor 1.4.1. Just not on Linux.

**Comment by skemb321** [comment]
@mitar yes same error. Sorry I passed out last night.

**Comment by mitar** [comment]
OK, then close this ticket and let's move discussion to #201.

**Comment by skemb321** [comment]
yep. closing
