### ISSUE TITLE
3.8.1 release is missing Linux binaries

### ISSUE THREAD

**Issue by mitar** [fourseven/meteor-scss#215]
Only Windows and Mac OS X has been published. `meteor publish-for-arch` for Linux should be run as well.

```
  "architecturesOS": [
    "os.windows.x86_32",
    "os.osx.x86_64"
  ]
```

**Comment by skemb321** [comment]
how does `meteor publish-for-arch` work? I read in Meteor 1.4.1 update that it's not mandatory anymore? Not sure.

**Comment by mitar** [comment]
It does not work for me without.

It works the same as it worked before. Maintainer of the package will know.

**Comment by mitar** [comment]
This issue is duplicate of #201.
