### ISSUE TITLE
Failed download from meteor

### ISSUE THREAD

**Issue by apps4av** [fourseven/meteor-scss#220]
zkhan@zkhan-ThinkPad-E520:~/app$ meteor add materialize:materialize
 => Errors while adding packages:             

While loading package fourseven:scss@3.2.0:
error: Command failed:
/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node":
HTTP error 404 Not Found
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous>
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient
(_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
(_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/npm-debug.log
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.2.0/linux-x64-46_binding.node":
HTTP error 404 Not Found
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous>
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse
(/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/node_modules/pangyp/node_modules/request/request.js:1255:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient
(_http_client.js:433:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete
(_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/zkhan/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node
scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/npm-debug.log

zkhan@zkhan-ThinkPad-E520:~/app$ vi /home/zkhan/.meteor/packages/fourseven_scss/.3.2.0.12lfg4f++os.linux.x86_64+web.browser+web.cordova/plugin.compileScss.os.linux.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-6x0oy9/npm-debug.log
zkhan@zkhan-ThinkPad-E520:~/app$

**Comment by Unforgiven-wanda** [comment]
Exact same issue. Waiting for fix as well.

**Comment by jamesabels** [comment]
Same there on OSX 10.11.6 but it seems to be an issue with the NPM package.

**Comment by jc2** [comment]
Same problem:

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading fourseven:scss@3.9.0...:
   error: Command failed: /root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --no-bin-links --update-binary
   module.js:327
   throw err;
   ^

   Error: Cannot find module '/tmp/mt-1sbvhvl/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-xb77rq/node_modules/node-sass/scripts/install.js'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Function.Module.runMain (module.js:441:10)
   at startup (node.js:139:18)
   at node.js:974:3

   npm ERR! Linux 4.4.0-36-generic
   npm ERR! argv "/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.5.0
   npm ERR! npm  v3.10.6
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/install.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /tmp/mt-1sbvhvl/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-xb77rq/npm-debug.log
   module.js:327
   throw err;
   ^

   Error: Cannot find module '/tmp/mt-1sbvhvl/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-xb77rq/node_modules/node-sass/scripts/install.js'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Function.Module.runMain (module.js:441:10)
   at startup (node.js:139:18)
   at node.js:974:3

   npm ERR! Linux 4.4.0-36-generic
   npm ERR! argv "/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
   npm ERR! node v4.5.0
   npm ERR! npm  v3.10.6
   npm ERR! code ELIFECYCLE
   npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the node-sass package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node scripts/install.js
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs node-sass
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls node-sass
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /tmp/mt-1sbvhvl/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-xb77rq/npm-debug.log


_________________________
Ubuntu 16.04 Server
NodeJs: 4.5
NPM: 2.15.9

**Comment by emirdeliz** [comment]
+1

**Comment by emirdeliz** [comment]
I solved this issue with copy manual of the file to dir /Users/<user>/.meteor/packages/fourseven_scss/.3.2.0.1f10i3t++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/node-sass/vendor/darwin-x64-46 

Look her for details: [https://github.com/sass/node-sass/issues/1162]( https://github.com/sass/node-sass/issues/1162)

**Comment by alecsandruchirosca** [comment]
+1

**Comment by theosp** [comment]
Hi,

Those of you who wish to keep using sass syntax in Meteor v1.4 and therefore have to use
version <= 3.3.3 of libsass due to issue: https://github.com/sass/node-sass/issues/1192.

You get the above error because there's no compiled sources for [v3.2.0 of libsass](https://github.com/sass/node-sass-binaries/tree/v3.2.0) - but [there are
for v3.3.3](https://github.com/sass/node-sass-binaries/tree/v3.3.3).

So I could solve the issue by downloading the current version of meteor-scss to my packages folder (it is commit cb2aba3292b1629f84b09d37c5bb861dde592777 at the time of writing).

And changed package.js to use: 

    'node-sass': '3.3.3' 

Instead of 3.10.0, which it's currently using, luckily the problem didn't begin in v3.3.3.

That's all!

@sebakerckhof perhaps we can add this to Readme, or even create a designated version for v1.4 .

**Comment by Fauphi** [comment]
@theosp I tried your solution but I still get an error saying: 

`Scss compiler error: top-level variable binding must be terminated by ';'`

Looks like the same error as with 3.10.0 but with another message. Seems like I have to downgrade to Meteor 1.3 again, finding a solution for this is too time consuming.

The strange thing is, if I compile the my main sass file with the node-sass CLI it works without any problems.

**Comment by Oyshoboy** [comment]
Guys, to resolve this problem add firstly 
`meteor add fourseven:scss`
coz meteors packages info is too old

And then, after installation of fourseven:scss u can install 
`meteor add materializa:materialize`

**Comment by sebakerckhof** [comment]
I'll close this issue since there's a workaround posted in this thread and we no longer support the older sass syntax.

**Comment by MagneticMule** [comment]
+1
