### ISSUE TITLE
ENOENT: open '/tmp/mt-4iuq3e/plugin.compileScssBatch.os/program.json'

### ISSUE THREAD

**Issue by Unforgiven-wanda** [fourseven/meteor-scss#226]
Hello, 
I have a project that I've been running on Windows for some time now. However, when I cloned my repo on my Ubuntu machine, when running `meteor run` I ran into the following:

```
/home/myuser/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-4iuq3e/plugin.compileScssBatch.os/program.json'
```

That is, however I try to install (or remove) fourseven:scss, it's just always the same error message. I've tried reinstalling node, npm, meteor, running `meteor npm rebuild` and the like to no avail.

I am at my wit's end. What could be causing this?
Thank you

**Comment by Unforgiven-wanda** [comment]
Fixed the issue by downloading the package from Github, extracting its folder it in a "packages" folder at the root of my project, deleting ".meteor/local" then running `meteor run` again.

Strangely enough, had to this for universe:i18n as well. All other packages work flawlessly.
Hope this helps somebody else. Closing.

**Comment by sebakerckhof** [comment]
Just a question since I've also seen this.
1) Did you run as root or not?
2) Did you find another way of solving in the meanwhile?

**Comment by Unforgiven-wanda** [comment]
> Did you run as root or not?

Yes. Sudo all the way.

> Did you find another way of solving in the meanwhile?

Nope. sorry.
