### ISSUE TITLE
Error to compile .sass

### ISSUE THREAD

**Issue by tiagoporto** [fourseven/meteor-scss#228]
I have the file `alert.sass`

```sass
.alert
  background: #FFF

```
I get the error: `Scss compiler error: Invalid CSS after ".": expected 1 selector or
   at-rule, was ".alert"`

METEOR@1.4.1.2
fourseven:scss@3.9.0

**Comment by tiagoporto** [comment]
I update to fourseven:scss@3.10.0, but the same problem.

**Comment by sebakerckhof** [comment]
indented syntax is currently not supported, please read the readme
