### ISSUE TITLE
Loading only select stylesheets for a certain route.

### ISSUE THREAD

**Issue by BioXD** [fourseven/meteor-scss#229]
HI!

First off, great package. Thanks for building it.

I have an admin area and would like to keep the styles from loading into the main app to reduce loading time, so I was wondering if there's any way to select which styles are loaded per route, template or component (using React as well).

**Comment by sebakerckhof** [comment]
Lazy loading is beyond the scope of this project.
It's up to meteor tool to support splitting app bundles and up to the framework to support loading them.
