### ISSUE TITLE
Issue after last update (materialize:materialize and fourseven:scss)

### ISSUE THREAD

**Issue by lunatolun** [fourseven/meteor-scss#230]
It was fine before update. No error logs in to the console.

When I remove and add both packages, the versions seem to be correct:
fourseven:scss           added, version 3.10.0
materialize:materialize  added, version 0.97.8

Errors:

Error: Scss compiler error: Undefined variable: "$medium-and-down"
TypeError: Package['materialize:materialize'] is undefined
ReferenceError: meteorInstall is not defined

**EDIT**
using Materialize 0.97.7 fixed the issue

**Comment by 3210jr** [comment]
+1 same problem except using 0.97.7 is not helping

**Comment by bryanlimy** [comment]
+1 using 
fourseven:scss 3.10.1
materialize:materialize 0.97.8
gives error:
materialize_materialize.js?hash=97b7fa9…:7826 Uncaught Error: Scss compiler error: Undefined variable: "$medium-and-down".

**Comment by joshuaburkhalter** [comment]
+1 same problem here

**Comment by keyscores** [comment]
I vote to close this issue. See correct issue here:
https://github.com/Dogfalo/materialize/issues/3905

The issue is with materialize:materialize at version 0.97.8 . The error goes away when downgrading materialize to 0.97.7 , and keeping fouseve:scss at the most updated version.

**Comment by sebakerckhof** [comment]
Closed per: https://github.com/Dogfalo/materialize/issues/3905
