### ISSUE TITLE
Documentation for Meteor 1.3 should state fourseven:scss@3.8.0_1

### ISSUE THREAD

**Issue by derwaldgeist** [fourseven/meteor-scss#235]
I just tried to update my Meteor 1.2 app to Meteor 1.3 and fell in the trap that the SCSS package wasn't compatible anymore. The update broke with an error. So I looked at the docs and those stated that I should pin fourseven:scss to version 3.8.0. But this only resulted in an error that there was no binary available for my system (MacOS). Finally, I found #201 where I learned that version 3.8.0_1 is the right version for Meteor 1.3. I recommend to update the docs accordingly.

BTW: Is there any chance to make fourseven:scss cross-version compatible? I am running multiple Meteor apps that are on different Meteor versions but share the same packages which require fourseven:scss.

**Comment by sebakerckhof** [comment]
@derwaldgeist I changed the readme. For the foreseeable future, fourseven:scss 4.5.0+ should remain compatible with new meteor versions.

**Comment by derwaldgeist** [comment]
Thanks!
