### ISSUE TITLE
Cannot find module './_Login.scss'

### ISSUE THREAD

**Issue by Nisthar** [fourseven/meteor-scss#236]
I am new to using this package. I have a react component in `/imports/client/components/Login/LoginWrapper.jsx` 
and the scss file for it as `/imports/client/components/Login/_Login.scss` 

I am trying to import this scss file in the loginwrapper component. But its giving this error `Cannot find module './_Login.scss'`

**Comment by sebakerckhof** [comment]
This error does not originate from `meteor-scss`. It's an error from meteor-tool. 
So you'll have to ask the question there and include a reproduction with it.

**Comment by Nisthar** [comment]
@sebakerckhof Yes, But it works if i use `.css` instead of `.scss`.
