### ISSUE TITLE
sourceComments set to map doesn't seem to generate sourcemaps

### ISSUE THREAD

**Issue by trymbill** [fourseven/meteor-scss#24]
I'm trying to get sourcemaps with the css output and for some reason I don't seem to be able to get the package to produce sourcemaps.

I've set my scss.json file to:

```json
{
    "sourceComments": "map"
}
```

but can't seem to find any sourcemaps generated. Any help much appreciated :)

**Comment by fourseven** [comment]
`2.0.0_1` has sourcemap support (finally!) - give it a try :hamster:
