### ISSUE TITLE
meteor update does not update to 4.5.0

### ISSUE THREAD

**Issue by s7dhansh** [fourseven/meteor-scss#241]
I am on Meteor 1.4.2.7. `fourseven:scss` is stalled at 3.13.0 saying that it is at the latest compatible version.
The README says that 1.4.1+ can use v4.5.0.

How can I update it?

**Comment by sebakerckhof** [comment]
You're probably using a package which specifies it wants to use fourseven:scss 3.13.0.
It might make sense for us to no longer follow the node-sass release version numbers, since our internal API is still compatible, but Meteor now thinks it's not because of the change in major version number.

**Comment by s7dhansh** [comment]
Ok thank you. I realized that the culprit was materialize.
