### ISSUE TITLE
Supporting for sass indented syntax

### ISSUE THREAD

**Issue by ediopia** [fourseven/meteor-scss#248]
I know what is a problem for importing sass files using indented syntax.

Is there any news to solve this problem? 

I switched bootstrap to bulma which was a huge mistake.

bulma does not provide scss files and I chose to use scss fork.

bulma is in developing stage and has a lot of bugs (A LOT)

I do not recommend meteor users use bulma.

**Comment by thebiltheory** [comment]
I had the same issue and @jgthms is not planning on converting the syntax. 

See [Issue](https://github.com/jgthms/bulma/issues/343)

The fork version hasn't been updated since 7 months by now. :(
I guess we'll have to go for another lib, or go hardcore and create everything from scratch. lol

**Comment by sebakerckhof** [comment]
node-sass seems to have no plans to support indented syntax with custom importers. We're depending on that so we also have no plans to support it.
