### ISSUE TITLE
Scss compiler error: _.without is not a function

### ISSUE THREAD

**Issue by zapaz** [fourseven/meteor-scss#252]
New version 4.5.3 generates lot of similar errors

`Scss compiler error: _.without is not a function`

4.5.0 works fine

**Comment by teknologist** [comment]
Same here

**Comment by Vandell63** [comment]
Same, I spend all the day and find nothing to fixed it.
+1

**Comment by tyvdh** [comment]
Same here. Please fix.

**Comment by sebakerckhof** [comment]
Should be fixed in 4.5.4
