### ISSUE TITLE
what version for Meteor 1.5?

### ISSUE THREAD

**Issue by minhna** [fourseven/meteor-scss#254]
I'm using meteor 1.5.1, I installed this package and the version is 3.13.0.
I can't update to newer version, it said: "The specified packages are at their latest compatible versions.".

Thank you.

**Comment by sebakerckhof** [comment]
You should use 4.5.4, try to manually set it in your versions file. There might be another package blocking an update by requiring 3.13.0, but then you should find out what package that is and see if they can update.
