### ISSUE TITLE
Losing sourcemaps when switching to PostCSS from seba:minifiers-autoprefixer

### ISSUE THREAD

**Issue by adrianbw** [fourseven/meteor-scss#256]
Seba's autoprefixing package is using a version of the autoprefixer that has some bugs, including min-content and max-content not getting prefixed in Safari. I've switched over to PostCSS, which is rendering styles correctly, but I'm losing sourcemaps. Any idea how to fix this?

**Comment by sebakerckhof** [comment]
I would guess this is an issue with the postcss plugin?
The sass plugin creates sourcemaps and these are further processed by the postprocessing plugins like the minifiers. Since it seems to work in my minification plugin I would expect something needs to change on Postcss side.
