### ISSUE TITLE
Feature request: live inject SCSS

### ISSUE THREAD

**Issue by marcelhadorn** [fourseven/meteor-scss#257]
It would be really nice if that was implemented in this package, instead of having to use a third party task runner like gulp to compile scss externally from meteor, and then inject styles.

If you ever worked with browser-sync, everything else than style injection feels just wrong.
And I'd love to start everything with just `meteor`.

Thanks for considering (or teach me better, if it's already possible?)

**Comment by sebakerckhof** [comment]
That would be a task for the meteor build tool instead of this package. We only compile scss to css for the files meteor tool requests. How this ends up in the application is out of our control.
