### ISSUE TITLE
Importing as ES6 modules breaks on-the-fly CSS update

### ISSUE THREAD

**Issue by derwaldgeist** [fourseven/meteor-scss#260]
My app is structured into local, private Atmosphere packages. This works well while I am using the following import syntax:

```js
api.addFiles('path/to/my/styles.scss');
```

If I change the file, Meteor re-compiles on the fly without a full hot-reload. I also get working source-maps.

However, as soon as I follow the ES6 module import approach recommended since Meteor 1.3, i.e. by defining a `mainModule` and importing the .scss files there (or from a React component file), two things happen:

1. Each change of a .scss file results in a full app reload
2. The links to the sourcemaps are broken. They point to the top-level of the app, like shown in this error message: `DevTools failed to parse SourceMap: http://localhost:3030/.home.session.scss.map` The .scss file actually resides in a subfolder of my package.

Is there a chance to prevent this? I would like to use import syntax to keep my React components aligned with the .scss files.

**Comment by derwaldgeist** [comment]
Not sure if this matters: But I have to use `fourseven:scss@3.8.1` for now, since this is the only version that works in combination with `reywood:bootstrap3-sass`. So I am not on the recommended version for 1.5, which would be 4.5.4. :-(

**Comment by derwaldgeist** [comment]
Update: I forked the bootstrap package to try out the recommended version of `fourseven:scss`. This fixed the source maps links, which is great, but still the app does a complete reload on every style change. Updated the issue title accordingly.

**Comment by sebakerckhof** [comment]
This is normal and outside of the control of this package.
If you import inside css inside your javascript, the css itself also becomes part of the javascript package (it basically becomes a string which is dynamically added to the DOM). Since Meteor cannot yet update parts of the javascript, it has to do a full reload.
