### ISSUE TITLE
No rebuild upon changes to partials

### ISSUE THREAD

**Issue by copleykj** [fourseven/meteor-scss#262]
I have a project that I'm using a main scss file under client and then importing most of the rest of the css from partials throughout the app. Whenever I change any of the partials the app doesn't recompile the css. If I change a line in the main file it will rebuild and pick up changes from the rest of the partials but this is a horrible workflow..

package version is 4.5.4 and meteor version is 1.5.1

**Comment by copleykj** [comment]
:+1:

**Comment by tomscholz** [comment]
Hi, can you share a screenshot of your folder structure or just some more information? Otherwise it is really hard/impossible to h

**Comment by sebakerckhof** [comment]
We would indeed need a reproduction to look further into this issue.

**Comment by copleykj** [comment]
Sorry guys.. not sure exactly what the issue was but this seems to be working fine now.
