### ISSUE TITLE
'data' option to addStylesheet must be a string

### ISSUE THREAD

**Issue by jpggvilaca** [fourseven/meteor-scss#267]
```
> meteor add fourseven:scss
 => Errors while adding packages:

While building package fourseven:scss:
/tools/isobuild/compiler-deprecated-compile-step.js:335:15: 'data' option to addStylesheet must be a string (compiling test/scss_tests.scss)
at Object.addStylesheet (/tools/isobuild/compiler-deprecated-compile-step.js:335:15)
at sourceHandler (packages/fourseven_scss/plugin/compile-scss.js:118:1)
```

node -v
v0.10.46

npm -v
3.10.5

meteor --version
Meteor 1.3.5.1

**Comment by jpggvilaca** [comment]
whoever gets to this, u just need to go that line, packages/fourseven_scss/plugin/compile-scss.js:118:1 and add a `toString()` to the end of the line.

**Comment by sebakerckhof** [comment]
Which fourseven:scss version does this concern?

**Comment by jpggvilaca** [comment]
2.0.1_2

**Comment by sebakerckhof** [comment]
That version is long outdated and no longer supported.
The readme contains a compatible version table. I'll close this for now, but can re-open if the issue still occurs with newer versions.

**Comment by jpggvilaca** [comment]
I was dealing with a legacy app with the locked version that I mentioned, so I need to fix that because It was impossible to update. That `toString` hack did the trick. But thanks :)
