### ISSUE TITLE
Conditional Loading?

### ISSUE THREAD

**Issue by wesleyfsmith** [fourseven/meteor-scss#268]
Is there a way to conditionally change a top level import based off a javascript variable? I'm trying to create a day-mode night-mode feature and ideally I would just import a different scss file at the top of the project.

I'm fine if there's a hacky solution that requires a page reload. Thanks!

**Comment by sebakerckhof** [comment]
No, there's no such thing provided by this package. And this should be dealt with at a different layer.
Meteor 1.6 supports dynamic imports, I don't know if that can also be used to dynamically import (s)css (never tried it). But that mechanism sounds like a decent solution for this problem.
