### ISSUE TITLE
No minification or concatenation occurring in --production

### ISSUE THREAD

**Issue by dtruel** [fourseven/meteor-scss#270]
Hello, and thanks for your work on meteor-scss! It's a very useful package!

When I run my app in production, it doesn't minify or concatenate any of the CSS.  So my application is loading a ton of CSS files.  How do I get it to concatenate and minify my css?  Because of how my application is structured, it doesn't matter the order of concatenation. I have 130 sass files in my project, so I think I could definitely increase load speed with concatenation and minification.

**Comment by sebakerckhof** [comment]
Minification and concatenation are not done by this plugin.

The meteor build pipeline has multiple steps. This plugin only concerns the compiling step (which runs in both debug and production mode). Minification is done in another step and for this you need another plugin (e.g. `standard-minifier-css`, which is the default one from meteor). If you then still don't get a minified css in production mode, you should create a reproduction and discuss the issue in the meteor repository.

**Comment by dtruel** [comment]
Oh, thank you!  I must have removed that package inadvertently.
