### ISSUE TITLE
[Bug] Problem with Meteor 1.7 + Vue-Component + Vue-Sass

### ISSUE THREAD

**Issue by thearabbit** [fourseven/meteor-scss#274]
- [ ] Feature request
- [x] Bug report
- [ ] Question

`meteor` 1.7:

`fourseven:scss` 4.9:

Get error when `meteor run`

![image](https://user-images.githubusercontent.com/4495160/41265030-4fda0022-6e1a-11e8-906e-69e31ed9957b.png)

**Comment by sebakerckhof** [comment]
That's not coming from this package.

Stack trace tells you it comes from `packages/vue-component-sass/vue-sass.js:12:15`

**Comment by thearabbit** [comment]
Thanks for your reply, But when I tried remove `fourseven:scss` It work fine
