### ISSUE TITLE
Minify and autoprefix for scss files imported as modules

### ISSUE THREAD

**Issue by fabien-h** [fourseven/meteor-scss#277]
In a react file, we can import an scss file as a module. `import './myStyles.scss';` will import the styles and inject them as a `<style/>` tag in the head thanks to the `ecmascript` package. And the `meteor-scss` package will transpile scss to css and manage the scss imports.

Great, it works.

But how do we minify and autoprefix those modules ? I tried to add `seba:minifiers-autoprefixer` without luck.

**Comment by fabien-h** [comment]
Great.

Although, minification and source mapping happen. But I don't see the auto-prefixing. I ask on the meteor issue

**Comment by sebakerckhof** [comment]
are you using `seba:minifiers-autoprefixer` ? 

The default meteor minifier doesn't have auto-prefixing

**Comment by fabien-h** [comment]
Yep. If I put an scss file in the /client folder, it is auto prefixed and included in the css bundle. But when I import them as a js module, they are not.

**Comment by sebakerckhof** [comment]
Closing, since this is to be solved by Meteor instead of this package
