### ISSUE TITLE
Question: what is the best way to set precision?

### ISSUE THREAD

**Issue by ignl** [fourseven/meteor-scss#281]
Buttons in bootstrap-sass are misaligned (issue: [here](https://github.com/twbs/bootstrap-sass/issues/409)) because of precision too low. This seems to be a common problem. What is the way to increase precision for meteor-scss?

**Comment by sebakerckhof** [comment]
I published a new version `4.9.3` with increased precision.

**Comment by ignl** [comment]
Thanks for such a quick fix. I can confirm misaligned buttons on bootstrap-sass are fixed for me now.
