### ISSUE TITLE
Importing files from node_modules that include other files not working as expected

### ISSUE THREAD

**Issue by derwaldgeist** [fourseven/meteor-scss#282]
I am using the professional version of Fontawesome. This package requires me to import this file:

```scss
@import '{}/node_modules/@fortawesome/fontawesome-pro/scss/fontawesome';
```

The `fontawesome.scss` consists of relative imports like this:

```scss
@import 'variables';
... other imported files ...
```

The referenced files are prefixed with an underscore like this: `_variables.scss`.

However, these imports are ignored. Instead I get error messages because the variables haven't been set. If I patch the references to

```scss
@import './variables';
... other imported files ...
```

the references work. But as this is an external module, it does not make sense to monkey-patch these paths.

I also tried to add the whole path to `includePaths`, but this did not work either.

**Comment by derwaldgeist** [comment]
Just saw #239. I guess that's the same problem.

**Comment by sebakerckhof** [comment]
Closing as duplicate
