### ISSUE TITLE
absolute path in scss convert to relative path when in production

### ISSUE THREAD

**Issue by imhazige** [fourseven/meteor-scss#284]
- [ x] Bug report

`meteor` version:1.8

`fourseven:scss` version:latest

$bg: url('/css/bg_signin.png');

this work in local dev mode.

the created style in browser have the prefix / so . it is correct

but when deploy with production build, the style change to relative path css/bg_signin.png

it did not work anymore.

**Comment by sebakerckhof** [comment]
That's not a bug in meteor-scss
See: https://github.com/meteor/meteor/issues/10247 (and specifically https://github.com/meteor/meteor/issues/10247#issuecomment-432116487 )

**Comment by imhazige** [comment]
will set my ROOT_URL = https://xxx/ sove the problem?
