### ISSUE TITLE
Replace libsass with dart-sass

### ISSUE THREAD

**Issue by m-vinc** [fourseven/meteor-scss#285]
- [ ] Feature request
- [ ] Bug report
- [X] Question

Hey.
I use bulma in my project which is writed using the indented syntax, so i can't import bulma using your package because the libsass don't support this syntax.
I have an idea: replace the node-sass package with [dart sass](https://www.npmjs.com/package/sass), which don't need external dependencies like ruby sass or libsass. I forked your package, switch node-sass with sass and It worked well, now I can import bulma without problem.

I need to know what do you think about that and if there is a chance that your package use dart-sass in the future :)

**Comment by sebakerckhof** [comment]
I'll give it a try on some large code bases to see if the cpu/memory performance of dart-sass is acceptable in comparison with node-sass. I'll come back to this.

**Comment by sebakerckhof** [comment]
I decided not to switch to dart-sass based on performance being 3x slower than libsass: https://github.com/sass/dart-sass/blob/master/perf.md 
libsass being ~1.5 times as fast as dart-sass on Dart VM, which again is ~3 times faster than dart-sass on node. So in total ~4.5 times slower.
