### ISSUE TITLE
Bug: the "original" argument must be of type function

### ISSUE THREAD

**Issue by W1-PopelierE** [fourseven/meteor-scss#287]
When using this package at version 4.10.0 with Meteor 1.8.1 (beta.20) the following errors occurs:

`While loading plugin `compileScssBatch` from package `fourseven:scss`:
   internal/util.js:214:11: The "original" argument must be of type function`

This error does not occur when I pin the version of this package to 4.9.3.

Running on Windows 10 x64 with Node.js 8.15.1.

@koenlav

**Comment by sebakerckhof** [comment]
I can't seem to reproduce this (at least on linux, don't have a windows system around for the moment).
Could you create a small reproduction where you experience the issue.

**Comment by KoenLav** [comment]
It seems that this issue was caused by installing this package (or node-sass) using Node.js 10 and later reverting to Node.js 8 on the system.
