### ISSUE TITLE
Adding package gives error

### ISSUE THREAD

**Issue by amanagarwal2189** [fourseven/meteor-scss#288]
- [ ] Feature request
- [x] Bug report
- [x] Question

`meteor` version:1.7.0.5

`fourseven:scss` version:3.13.0

I included this package in my meteor project and now I am getting the following error. Not able to remove/add anything else either.

=> Errors while initializing project:

While loading package fourseven:scss@3.13.0:
error: Command failed: C:\windows\system32\cmd.exe /c C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.0/win32-ia32-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
gyp verb cli   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.11.4 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe
gyp verb check python version `C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir compiling against specified --nodedir dev files: C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle
gyp verb build dir attempting to create "build" dir: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe
gyp info spawn args [ 'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\.temp-xvxf8k.aa8bl\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\.temp-xvxf8k.aa8bl\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\.temp-xvxf8k.aa8bl\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags="
"--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jxue\AppData\Roaming\npm-cache\_logs\2019-03-12T19_22_30_819Z-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.0/win32-ia32-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
gyp verb cli   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.11.4 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe
gyp verb check python version `C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir compiling against specified --nodedir dev files: C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle
gyp verb build dir attempting to create "build" dir: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle\python\python.exe
gyp info spawn args [ 'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\.temp-xvxf8k.aa8bl\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\.temp-xvxf8k.aa8bl\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\.temp-xvxf8k.aa8bl\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\jxue\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_32\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0_2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\jxue\\AppData\\Local\\.meteor\\packages\\fourseven_scss\\3.13.0\\plugin.compileScssBatch.os\\npm\\node_modules\\meteor\\compileScssBatch\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags="
"--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\jxue\AppData\Local\.meteor\packages\fourseven_scss\3.13.0\plugin.compileScssBatch.os\npm\node_modules\meteor\compileScssBatch\node_modules\.temp-xvxf8k.aa8bl\node_modules\node-sass
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jxue\AppData\Roaming\npm-cache\_logs\2019-03-12T19_22_30_819Z-debug.log

**Comment by sebakerckhof** [comment]
https://github.com/fourseven/meteor-scss#compatibility
