### ISSUE TITLE
Add Compass support

### ISSUE THREAD

**Issue by wizonesolutions** [fourseven/meteor-scss#3]
Is it possible to make this work with Compass? Currently getting:

`/Users/kevin/meteor/apps/scheduler/sass/screen.scss: Sass compiler error: :1: error: error reading file "compass"`

**Comment by LeCoupa** [comment]
Yes, Meteor-Compass works great.

     meteor add francocatena:compass

Check [README](https://github.com/francocatena/meteor-compass/) for package configuration.

**Comment by askucher** [comment]
You need just sass and bower 

```sh
bower install compass-sass-mixins

```

```sass
@import "bower_components/compass-sass-mixins/lib/compass"
//@import "node_modules/compass-sass-mixins/lib/compass"

/*
use your sass mixins here
*/
```

repository and list of funtions
```
https://github.com/askucher/compass-sass-mixins
```
