### ISSUE TITLE
Pluggin Chrome Devtools Into Project

### ISSUE THREAD

**Issue by JoshuaSoileau** [fourseven/meteor-scss#31]
Does this package support using Chrome Devtools 'Workspace's to plug into your filesystem so you can save the changes to your disk in the browser?

My compiled stylesheet with this package only contains a minified css file.

**Comment by fourseven** [comment]
This will require sourcemaps to even consider, which will be looked at once node-sass 2.0.0 is stable.

**Comment by sebakerckhof** [comment]
This seems to work now.
