### ISSUE TITLE
Allow packages that rely on fourseven:scss to add an include path

### ISSUE THREAD

**Issue by reywood** [fourseven/meteor-scss#40]
This is an idea to make it easier for users to include partials provided by other packages such as reywood:bootstrap3-sass or matthew:foundation5-sass. Currently, the user has to include something along the lines of `@import '.meteor/local/build/programs/server/assets/packages/reywood:bootstrap3-sass/bootstrap';` in their scss file to use these packages. One problem with this is that some systems apparently have an underscore instead of a colon in the path.

Here's a half baked idea I came up with to maybe solve this problem. In a package that relies on fourseven:scss, one would include a JS file on the server (i.e. `api.addFiles([ "include-path.js" ], "server")`). In that file, they would have something like `Scss.addIncludePath("path/to/reywood:bootstrap3-sass")`, and meteor-scss could push that value onto the `includePaths` array option. Then users could just add `@import 'bootstrap';` to their scss file. I haven't quite figured out how to get the real path to the package in a consistent way, but figured this would be food for thought.

**Comment by bompi88** [comment]
+1

**Comment by sebakerckhof** [comment]
3.4.0-beta1 supports cross-package imports for this.
