### ISSUE TITLE
file to import not found or unreadable

### ISSUE THREAD

**Issue by randallagordon** [fourseven/meteor-scss#48]
Hello! I note in the README you mention using Bourbon and Neat via meteor-bower and I'm attempting to do just that (I'm using "mquandalle/meteor-bower").

The issue I've got is that after a `meteor reset` or in a fresh test environment on Travis-CI, I'm running into what appears to be a race condition with dependency installation. On the first run, I get `file to import not found or unreadable: "bourbon"` errors which do not occur on subsequent runs of meteor.

Digging through the Meteor docs I don't see a clear way to specify build steps which depend on one another. Any insights as to how to solve this?

**Comment by fourseven** [comment]
I've published a beta based on node-sass 2.0.0-beta, can you see if this is still a problem with this version?

**Comment by randallagordon** [comment]
I'm running into constraint issues with the Bourbon and Neat packages, taking a bit too long to figure out a work around at the moment so I'll have to pick it up and try again over the weekend.

**Comment by AnkitTheCoder** [comment]
I'm unable to get the error disappear at all. Even the second attempt results in the same 

    file to import not found or unreadable

The folder does not even exist in my local docs

    .meteor/local/build/programs/server/assets/packages/<package>

**Comment by sebakerckhof** [comment]
This isn't relevant anymore.
