### ISSUE TITLE
Cannot load the plugin in meteor on a Centos 6

### ISSUE THREAD

**Issue by chansdad** [fourseven/meteor-scss#53]
seeing the following error
While Loading plugin `fourseven:scss` from package `fourseven:scss`:
module.js:356:32: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.meteor/packages/fourseven:scss/.1.0.0.ey0yds++os.linux.x86_64+web.browser+web.cordova/plugin.fourseven:scss.os.linux.x86_64/npm/fourseven:scss/node_modules/node-sass/bin/linux-x64-v8-3.14/binding.node)

**Comment by tedgoldstein** [comment]
I'm having this same problem. Do I have to upgrade my OS to CentOS7 on a production sever just to get access to a library?

**Comment by fourseven** [comment]
You should be able to add a compatibility library for glibc 2.14, but I'm not sure what it'll be called on CentOS. I'm going to do another release once the second node-sass beta is out, but I've been building the x64 linux releases on nitrous.io, so I have very little control over libraries.

**Comment by fourseven** [comment]
Can you test the 2.0.0-beta release please? It's built with the meteor-supplied VMs (which are a thing now, awesome!). This method is going to be my new standard, unless it's still causing issues on older linux distributions.

**Comment by fourseven** [comment]
Closing due to no response.
