### ISSUE TITLE
Installing 2.0.0-beta

### ISSUE THREAD

**Issue by aaronagray** [fourseven/meteor-scss#54]
Do you know of a simple way to add this at version `2.0.0-beta`? 

When I run `meteor add fourseven:scss`, it installs version 1.0.0, which appears to use an older version of node-sass than I'd like. However, when I download and include the meter-scss package locally, `meteor add meteor-scss` installs version 2.0.0-beta, which works for my purposes.

We finally have Susy playing well with LibSass, so once this is running I can get Susy fully integrated into Atmosphere for us. :)

**Comment by fourseven** [comment]
Hi @aaronagray - I was waiting for beta2 because I was trying to get source maps going at the same time, but those are bugged in the original beta. There's actually no reason to not release this beta though (without it), so I'll get to that now.

**Comment by aaronagray** [comment]
Awesome! That would be fantastic. I'm certainly happy to wait for source maps in favor of getting other beta2 features.

**Comment by fourseven** [comment]
It's live @aaronagray! 🐳

**Comment by aaronagray** [comment]
Woo! Did you publish it to Atmosphere? Still getting version 1.0.0 when I use `meteor update` or `meteor install fourseven:scss`

**Comment by aaronagray** [comment]
It works locally exactly as expected. :shipit: :smiley_cat:

**Comment by fourseven** [comment]
Cool, you found it? It's probably hidden as it's flagged as beta.

**Comment by aaronagray** [comment]
I cloned it into a local packages directory because I didn't see it on Atmosphere yet. Getting this from `meteor install fourseven:scss@2.0.0-beta`. 

```
 => Errors while adding packages:             
                                              
While checking for fourseven:scss@2.0.0-beta:
error: No compatible build found
```

I've tried a few other version flags to no avail. f

**Comment by fourseven** [comment]
Strange, `meteor show fourseven:scss` returns the following:

```
Version 0.9.4       Style with attitude.
Version 0.9.5       Style with attitude.
Version 0.9.6       Style with attitude and autoprefixer.
Version 1.0.0       Style with attitude and autoprefixer.
Version 2.0.0-beta  Style with attitude and autoprefixer.
```

**Comment by fourseven** [comment]
sorry try again @aaronagray - I needed to publish-for-arch the mac os x version, even though that was the platform the initial publish was done against...

**Comment by aaronagray** [comment]
Hah, that's good to know. :smile_cat: I just ran `meteor add fourseven:scss@="2.0.0-beta"` again and it installs properly. Sass, Susy, and Meteor are all playing well together. Yay! Great work.

**Comment by fourseven** [comment]
That's very cool, thank you for the nudge to release this version. All that's left is source maps now :racehorse:

**Comment by aaronagray** [comment]
That's great. Thanks for making it happen. I'm not sure where to start on source maps, but do let me know if I can help. :athletic_shoe:
