### ISSUE TITLE
"Flash of unstyled content" problems when using the package

### ISSUE THREAD

**Issue by johanbrook** [fourseven/meteor-scss#57]
Hi!

We're using this package, and it works very well, except that we've experienced FOUC ("Flash Of Unstyled Content") recently. We're using Iron Router, and when switching routes, the markup is briefly rendered unstyled. 

I don't know whether this is a Meteor issue, an issue with the compile system, or with this plugin. At least it would be nice with some directions or thoughts regarding this.

We're not doing anything special – just having a semi-large SCSS foundation used with an Iron Router powered Meteor app on 1.0.2.1. Earlier we compiled the SCSS outside of meteor and had a hardcoded `link` element in the `head` tag in `index.html`.

Is Meteor actually inserting the `link` element for the resulting SCSS in the `head` async on page load?

**Comment by fourseven** [comment]
Hi @johanbrook - is this in all environments? I'm actually unsure at what stage of the render cycle Meteor injects the outputted CSS file, but I'll do some digging for you.

**Comment by johanbrook** [comment]
Hi! There was an issue in another location in our app, so our FOUC problem is not related to this package :) Thanks for replying!
