### ISSUE TITLE
No compatible builds found

### ISSUE THREAD

**Issue by fredrikekelund** [fourseven/meteor-scss#59]
Happened to remove this package just now, and when I tried re-adding it, Meteor complained that it couldn't find any compatible builds. I'm running 64-bit Linux.

	$ meteor add fourseven:scss
	 => Errors while adding packages:

	While checking for fourseven:scss@1.2.3:
	error: No compatible build found

**Comment by fredevery** [comment]
Likewise +1

**Comment by fredrikekelund** [comment]
To anyone else experiencing this in need of a temporary workaround, the 0.9.6 version appears to work, so while waiting for a fix you can use:

    $ meteor add fourseven:scss@0.9.6

**Comment by fourseven** [comment]
There's a 2.0.0_beta_1 which works quite well, I tried to make a 1.2.3 stable release but node-sass's build was quite broken on that version for old GCC versions, which is what the build boxes use. I've hidden that release again.
