### ISSUE TITLE
error while updating to meteor 1.0.3.1

### ISSUE THREAD

**Issue by joernroeder** [fourseven/meteor-scss#61]
Hey,
i've got the following error while updating my project to the latest meteor version:

```
updated to Meteor 1.0.3.1.
=> Errors while upgrading packages:

While checking for fourseven:scss@1.2.3:
error: No compatible build found
```

**Comment by mmccoy** [comment]
Any chance you found a workaround for this, I'm also experiencing it..

**Comment by fourseven** [comment]
please check the issue history, #60 has more details including a work-around

**Comment by tinowell** [comment]
I used the #60 workaround and everything inside @media queries disappeared. Everything worked fine until I ran meteor update. I've switched to a different scss package in the meantime.

**Comment by fourseven** [comment]
Does 0.9.6 work for you @tinowell ?

**Comment by tinowell** [comment]
0.9.6 did indeed work. I had only tried 1.0.0.

**Comment by fourseven** [comment]
Thanks, I'll add a note to #60 and will leave this open so other people are aware of the issue (until I hear back from the meteor/meteor team).

**Comment by dcs619** [comment]
+1 for the error.  Running meteor add fourseven:scss@=0.9.6 worked for me.

**Comment by fourseven** [comment]
The meteor issue is meteor/meteor#3524 (for reference).

**Comment by fourseven** [comment]
New (or old) meteor issue - https://github.com/meteor/meteor/issues/2459 - I'll re-release the 2.0.0 beta to make it the preferred package.

**Comment by althe3rd** [comment]
I assume the issue is still open for good reason just wanted to add that I also just tried to add the package to my project with the latest version of meteor and received the same error "no compatible build found".

**Comment by fourseven** [comment]
Ended up using EC2 instances with GCC-4.9 and there's now a 1.1.4 and 1.2.3 build available for all platforms.
