### ISSUE TITLE
Can't compile locally using Windows preview

### ISSUE THREAD

**Issue by fredrikekelund** [fourseven/meteor-scss#64]
Official Meteor support for Windows is right [around the corner](https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows) and I'm testing the preview they've published. I've encountered an error when adding `fourseven:scss` as a local package - I get the following error:

    While loading plugin `scss` from package `scss`:

    C:\Git\MeteorDataTool\meteor\packages\scss\.npm\plugin\scss\node_modules\node-sass\lib\index.js:21:11:
    `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding
    (C:\Git\MeteorDataTool\meteor\packages\scss\.npm\plugin\scss\node_modules\node-sass\lib\index.js:21:11)
    at Object.<anonymous>
    (C:\Git\MeteorDataTool\meteor\packages\scss\.npm\plugin\scss\node_modules\node-sass\lib\index.js:211:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._.extend.Npm.require
    (C:\Users\Fredrik\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\bundler.js:1331:22)
    at Package (packages/scss/plugin/compile-scss.js:2:1)
    at <runJavaScript-80>:119:4
    at <runJavaScript-80>:126:3

The relevant line probably being `libsass bindings not found. Try reinstalling node-sass?`

While this is an error thrown by node-sass and not fourseven:scss, it seems to be an issue specifically when node-sass is installed by Meteor, since I can install it elsewhere on my system using just npm and it works fine.

I'd be happy to help fix this, but I was wondering if you (or anyone) has an idea of what could cause this problem?

**Comment by fourseven** [comment]
Honestly, the platform specific build chain doesn't support windows yet - so I'm not surprised that the released packages don't support it. Are their build boxes for windows in beta?

**Comment by fredrikekelund** [comment]
Nope, no build boxes yet. I suppose you have a point, they haven't said anything about what they intend to do with binary packages for Windows, so there might be further support for that in the works. 

But still, a lot of npm packages do compile properly when wrapped in a Meteor package, so I thought I'd raise the question to see what to make of it in this case

**Comment by fourseven** [comment]
I'll have a poke around this week and see what I can find. Which version of the scss package are you installing?

**Comment by fredrikekelund** [comment]
Cool! I downloaded the repo at the latest version (2.0.0-beta2 at the time, I believe) and added it as a local package.

**Comment by fredrikekelund** [comment]
I tried raising a general question around binary packages and Windows in the [windows preview issue tracker](https://github.com/meteor/windows-preview/issues/45), but haven't gotten any response there yet.

**Comment by fredrikekelund** [comment]
It seems that the node binary that comes bundled with Meteor is 32-bit. I'm not sure whether this is what causes the problem, but at the same time I can see that the node-sass package seems to be downloading libsass bindings for 64-bit (which is what my OS, which is Windows 8.1 btw, is running).

**Comment by dandv** [comment]
I get as well

> While checking for fourseven:scss@2.0.0_1
> error: No compatible build found

I have a Windows machine. How can I help?

BTW there have been some updates in https://github.com/meteor/windows-preview/issues/45

**Comment by fredrikekelund** [comment]
The Meteor team published a release candidate (0.3.0) the other day, and some [advice for packages with binary dependencies](https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview) as well as regarding [generally publishing packages cross platform](https://github.com/meteor/meteor/wiki/Building-cross-platform-packages-for-Meteor). Have you had a chance to try to publish the package with the latest Meteor?

**Comment by fourseven** [comment]
I'll have a look this weekend. I got very burned by this last time I tried (hence why there's a 2.0.1_2 and 2.0.1_3 release) so I'll see how it goes this time around.

**Comment by fourseven** [comment]
Since it's starting to gain traction, here's where it's failing now. https://github.com/meteor/windows-preview/issues/108 - This is a WIP, hope to have a working version eventually.

**Comment by fourseven** [comment]
Actually make that https://github.com/meteor/windows-preview/issues/105

**Comment by fourseven** [comment]
Hah just realised we'd be discussing the same issue @fredrikekelund - do you have a windows box to test `fourseven:scss@2.0.1_5`? If it works I will close this (it's published, don't have a windows box handy though).

**Comment by fredrikekelund** [comment]
Haha yeah, I've been eager to see this fixed.

It works, both downloading it and using it :tada: Actually it works even if I'm using `WINDOWS-PREVIEW@0.3.0` to run the app

**Comment by jakobrosenberg** [comment]
Works for me now. Thanks!

**Comment by fourseven** [comment]
Cool :balloon:
