### ISSUE TITLE
Update to node-sass to 1.1.4?

### ISSUE THREAD

**Issue by scott-mcpherson** [fourseven/meteor-scss#65]
Hey @fourseven ,

Do you have any plans to publish a release to meteor for node sass 1.1.4 support? I'm creating a package that uses foundation for apps and node sass 1.1.4 is required for the sass in that package. 

As a temporary fix I've cloned you scss package and released it with 1.1.4: https://github.com/RainHaven/meteor-sass

But I'm only running OS X and so I can't publish the package for linux support because Meteors publish-for-arch requires publishing from the targeted operating system.

Does fourseven:scss include support for Linux?

**Comment by fourseven** [comment]
Hi @scott-mcpherson - I've had a few problems with the 1.x versions of node-sass and building them on linux (see the numerous issues about 1.2.3 and the broken package it's created), but if you like I can try and build 1.1.4.

**Comment by fourseven** [comment]
Alright the standard build boxes won't handle 1.x versions (GCC is too old), I'll try and get two ubuntu ec2 instances to finish publishing it.

**Comment by fourseven** [comment]
Done, fixed up 1.2.3 while I was at it.

**Comment by scott-mcpherson** [comment]
Awesome! Thanks @fourseven
