### ISSUE TITLE
Can't seem to find scss.json?

### ISSUE THREAD

**Issue by livvyjeffs** [fourseven/meteor-scss#71]
I just installed this, but can't seem to find scss.json to give instructions on where to send the compiled code. How would I link the built CSS files into my .html file?

**Comment by fourseven** [comment]
The `scss.json` file is optional. Is it throwing an error for you @livvyjeffs? Once this is installed any *.scss/*.sass file (anywhere in the project) will be linked/injected into your output HTML, nothing else is required.

**Comment by livvyjeffs** [comment]
You're right, this works amazingly well! Out of curiosity though, where is the scss.json file? I am very glad that it works, but I'm also a bit curious as to what's going on under the hood. Thank you!

**Comment by fourseven** [comment]
Of course it does, it's Meteor! You create the `scss.json` yourself at the root of your project - which enables the more advanced features (autoprefixer for example). It's all going through node-sass under the hood.
