### ISSUE TITLE
Segfault after upgrade from 1.0.0 to 2.0.1_4

### ISSUE THREAD

**Issue by TimFletcher** [fourseven/meteor-scss#73]
As part of upgrading all my packages, I'm now getting a segmentation fault when trying to start my meteor server. Removing `fourseven:scss` fixes this.

This is my upgrade output — https://gist.github.com/TimFletcher/620226f44c70f1eb393c

I'm wondering if it's something related to the libsass version?

This is what I get when starting the server:

```
meteor --settings settings/development.json
[[[[[ ~/code/personal/linkmetrics ]]]]]       

=> Started proxy.                             
=> Started MongoDB.                           
Segmentation fault: 11ation 
```

**Comment by TimFletcher** [comment]
Should mention I'm using OS X Yosemite on a 2014 MBP, not Windows.

**Comment by fourseven** [comment]
Hi Tim, 
After a quick google search I found (this)[http://stackoverflow.com/a/28158992] - do those steps help it? Does it segfault from a new project too (`meteor create test; cd test; meteor add fourseven:scss; meteor`)?

**Comment by TimFletcher** [comment]
Hey,

Yes. I'd tried those steps. When meteor dies it does leave a process running that I need to kill using those steps. Restarting meteor gives the same error again though.

I tried your new project approach and it worked fine so I guess there's some other issue elsewhere. I'll try removing the other packages one by one until it works. Thanks!

**Comment by fourseven** [comment]
Cool, let me know which packages aren't playing nicely together!

**Comment by TimFletcher** [comment]
Well, rather disappointingly, a clean install of all the packages in a new meteor app will start just fine. So I suppose it's something in my code. Most likely my SCSS I guess so I'll start removing that.

**Comment by TimFletcher** [comment]
So it looks like the modulus operator doesn't work. This code (from https://github.com/thoughtbot/neat) is what causes the segfault:

```scss
  @else if length($query) % 2 == 0 {
  //  $query: append($query, $total-columns);
  }
```

There's a [closed issue](https://github.com/sass/libsass/issues/857) for this in libsass.

I've managed to work around this for now by installing an older version:

    meteor add fourseven:scss@1.0.0

Would love to get all this working with the latest versions but I'm good for now. Thanks for your help.

**Comment by fourseven** [comment]
Ah interesting, I'll leave this open - it should be fixed in the 3.0.0-betas which I need to write this weekend.

**Comment by fourseven** [comment]
Update @TimFletcher - adding pre-release NPM packages to a Meteor package isn't really possible, so I'm waiting for the stable 3.0.0 to come out. Sorry about the frustrations in the mean time.

**Comment by TimFletcher** [comment]
No problem! I'm fine working with the older one for now. Doesn't seem to be causing any issues. Appreciate the update though!

**Comment by fourseven** [comment]
Just triaging these issues, there's v3.0.0 out and I'll get v3.1.1 out soon too, both which should handle this again.

**Comment by TimFletcher** [comment]
This was fixed long ago so I'm closing to reduce open issue noise. Thanks for the fix!
