### ISSUE TITLE
includePaths in scss.json not working

### ISSUE THREAD

**Issue by backnight** [fourseven/meteor-scss#76]
The includePaths is not working.
Trying to add the ".meteor/" for any package installed via bower and no .scss file are detected and added to the compilation.

**Comment by thisisbrianhan** [comment]
Can you show how you're writing your includePaths? Even better if you can link to your repo.

**Comment by backnight** [comment]
It's a private repository.

./.bowerrc :
{
  "directory": ".meteor/local/bower"
}

./scss.json :
{
  "useIndex" : true,
  "indexFilePath" : "main.scss",
  "includePaths": [
    ".meteor/local",
    ".meteor/local/bower/foundation/scss"
  ]
}

I'm trying to add the foundation framework for the compilation.
If I change the .bowerrc directory (to a visible folder), foundation files are detected and compiled.
If the .bowerrc points to an hidden directory, nothing happen.

**Comment by fourseven** [comment]
Are you restarting meteor when you change the `scss.json` file? It doesn't pick up changes until you stop and start it again.

**Comment by sebakerckhof** [comment]
Closing in favor of https://github.com/fourseven/meteor-scss/issues/124
