### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by n0ne** [fourseven/meteor-scss#80]
Why files that begin with an underscore("_") are ignored?
Is it a bug or a feature?

**Comment by fourseven** [comment]
Hi @n0ne - this is expected, files with underscores at the start are called partials and should not compile themselves, only be imported through other files. See [here for more information](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials).

**Comment by n0ne** [comment]
I see, thanks!
