### ISSUE TITLE
Windows v3.0.0 release

### ISSUE THREAD

**Issue by fourseven** [fourseven/meteor-scss#83]
This isn't currently working, waiting on https://github.com/sass/node-sass/pull/931 or similar... please use v2.1.1 in the meantime.

**Comment by udnaan** [comment]
Should've looked here before I spend a few hours trying to debug the slowness.

**Comment by MichelPaus** [comment]
Thank you for putting this up here, looking forward to the 3.0.0 Win release!

**Comment by pmary** [comment]
Me too, do you plan to publish a compatible version ?

**Comment by fourseven** [comment]
Yes, but as `v3.0.1` - that will be the first 3.x release for windows (since v3.0.0 just won't build via Meteor). Here's the latest issue, which is already fixed in master - https://github.com/sass/node-sass/pull/943, and should be in `v3.0.1` of node-sass.

**Comment by fourseven** [comment]
fixed in `v3.1.1`

**Comment by MichelPaus** [comment]
Awesome, thanks a lot!
