### ISSUE TITLE
Can't get source maps to work

### ISSUE THREAD

**Issue by AdamBrodzinski** [fourseven/meteor-scss#85]
I'm trying to get the source maps to work but it just keeps referring all locations to the last selector of main.scss. I also tried to use the Ruby sass and it was just referencing the css file (even though the ruby version was creating a main.css source map).

I've also went through all of the online guides and made sure source maps are enabled in chrome and I added the project folder to the 'workspaces' area.

Any ideas? I've burned through an hour trying to get it to work :disappointed: 

For example this top rule should be in `'client/styles/_typography.scss'` and is included in `client/styles/main.scss`.

![screen shot 2015-05-14 at 3 55 08 pm](https://cloud.githubusercontent.com/assets/1445367/7640682/b05e5f5e-fa52-11e4-846d-9facc5610f03.png)

**Comment by fourseven** [comment]
Are you using autoprefixer as well? Sourcemaps with libsass are still a little terrible, but are fast getting better.

**Comment by ptim** [comment]
I've been having this issue, too. In my project, disabling autoprefixer allows sourcemaps to resolve to the correct source file. I've got autoprefixer operating in my committed scss.json, but switch it off whilst working, and never commit the updated/temporary scss.json.

**Comment by derwaldgeist** [comment]
I disabled autoprefixer, but still have the problem that the sourcemaps are not working reliable. Anything else one could do to fix this? I used libsass in Brackets SASS before, here I had no problems.

**Comment by dj0nes** [comment]
I'm having the same problem - all source map links point to the line of the last top-level selector.

Disabling Autoprefixer with 
```javascript
"enableAutoprefixer": false'
```
in scss.json does not help.

**Comment by Todilo** [comment]
Any news on this. I get a similar problem where the source map just points to the wrong file and the wrong row.  Installed forseven and then reywood:bootstrap3-sass with only 1 scss file referencing bootstrap3.

Disabling did not help

**Comment by derwaldgeist** [comment]
+1 I would also appreciate very much if this source map problem would be fixed.

**Comment by sebakerckhof** [comment]
I've also had this issue, but haven't seen it with 3.4.0-beta1.

**Comment by sebakerckhof** [comment]
Closing, since this should be fixed in latest beta.

**Comment by derwaldgeist** [comment]
Wow, this sound great! Another reason to switch to Meteor 1.2 once it's stable again :-)
