### ISSUE TITLE
Error while trying to add the package to meteor in windows

### ISSUE THREAD

**Issue by shaunthomas999** [fourseven/meteor-scss#87]
Hi,

I got the following error while trying to add the package to meteor in my windows machine;
meteor add fourseven:scss
=> Errors while adding packages:

While checking for fourseven:scss@3.0.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform. 

Any suggestion for solving the problem?

**Comment by fourseven** [comment]
This is a duplicate of #83 – I need to release 3.1.1 which should fix this.

**Comment by shaunthomas999** [comment]
Ok. Thank you!

**Comment by fourseven** [comment]
It was released btw, so give 3.1.1 a go :+1:

**Comment by shaunthomas999** [comment]
Just tried it. Itz a go :+1:
