### ISSUE TITLE
Using scss.json in packages

### ISSUE THREAD

**Issue by SachaG** [fourseven/meteor-scss#88]
The readme says: 

> This package has options that can be specified in a scss.json file in the project's root directory. 

But what if you're using SCSS inside a package? Will including `scss.json` in the root of the package work?

**Comment by SachaG** [comment]
In case there's no easy way to fix this, would you accept a PR to make AutoPrefixer enabled by default?

**Comment by fourseven** [comment]
Hi @SachaG – it should currently handle individual `scss.json` files per package, let me know if that's not the case and I can look into it for you.

**Comment by SachaG** [comment]
Oh you're right, it does work. I just had to modify my CSS to force it to re-render. I'll update the docs.
