### ISSUE TITLE
It's not compile my package scss file

### ISSUE THREAD

**Issue by alayii** [fourseven/meteor-scss#91]
I add this package to my meteor project. this is my packages file:

meteor-platform
autopublish
insecure
iron:router
fourseven:scss
alayii:nervous-core

then I create a package. inside `lib/client/scss/` created a _header.scss file. package.js:

Package.describe({
  name: 'alayii:nervous-core',
  version: '0.0.1',
  // Brief, one-line summary of the package.
  summary: '',
  // URL to the Git repository containing the source code for this package.
  git: '',
  // By default, Meteor will default to using README.md for documentation.
  // To avoid submitting documentation, set this field to null.
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.1.0.2');

  api.use('iron:router@1.0.7');
  api.use(['fourseven:scss'], ['client']);
  api.use(['templating'], ['client']);

  api.addFiles('nervous-core.js');
  api.addFiles([
    'lib/client/templates/header.html',
    'lib/client/templates/index.html'
  ], ['client']);
  api.addFiles([
    'lib/client/scss/_header.scss'
  ], ['client']);

  api.export('Core');
});

Package.onTest(function(api) {
  api.use('tinytest');
  api.use('alayii:nervous-core');
  api.addFiles('nervous-core-tests.js');
});

but template not apply scss file. what I missed?

ps: fourseven:scss@3.1.1

**Comment by alayii** [comment]
ok, I got it.

It's *cannot* add a partial file. like _header.scss. must have a entry file, main.scss or something

**Comment by fourseven** [comment]
Sorry that you got to this before I had a chance to help, but that makes perfect sense, partials don't get outputted on their own, so it makes sense that you weren't seeing the file anywhere.

If you want to use a partial, you'll have to use a scss.json file in the main project, with an includePaths value set to the package dir - which will allow you to `@import` that file.
