### ISSUE TITLE
CSS output options?

### ISSUE THREAD

**Issue by NetOperatorWibby** [fourseven/meteor-scss#92]
First, thanks for this plugin, it's awesome. However, I would like to compress the output from my Sass files. Does anyone know how to do this?

**Comment by fourseven** [comment]
Any node-sass options (like `outputStyle`) can be put into the scss.json file and will be picked up. Set the desired output there, restart meteor and you should see the new formatting/compression.

**Comment by NetOperatorWibby** [comment]
See, I tried that and while my Sass compiled, it was never compressed. I gave up
and am using the Sass gem to watch amd compile my Sass like I want. I can close
this issue when I get off the train.

On Wed, May 27, 2015 at 5:38 PM, fourseven/meteor-scss
<reply@reply.github.com>
wrote:
Any node-sass options (like outputStyle ) can be put into the scss.json file and will be picked up. Set the desired
output there, restart meteor and you should see the new formatting/compression.

—
Reply to this email directly or view it on GitHub
[https://github.com/fourseven/meteor-scss/issues/92#issuecomment-106086729] .[https://github.com/notifications/beacon/ABOopKm1-lXj1l0rj9KTWb1lM_RXfgAZks5oNjDWgaJpZM4EsBJb.gif]

**Comment by jamiewilson** [comment]
I can't seem to get `outputStyle` to work either. This is my `scss.json`:

```
{
  "outputStyle": "compressed",
  "enableAutoprefixer": true,
  "autoprefixerOptions": {
      "remove": true
  }
}
```

Any idea where I might be going wrong?

**Comment by NetOperatorWibby** [comment]
I think the issue is the plugin/module itself.

On Thu, Jul 30, 2015 at 3:28 PM, fourseven/meteor-scss
<reply@reply.github.com>
wrote:
I can't seem to get outputStyle to work either. This is my scss.json :

{
  "outputStyle": "compressed",
  "enableAutoprefixer": true,
  "autoprefixerOptions": {
      "remove": true
  }
}


Any idea where I might be going wrong?

—
Reply to this email directly or view it on GitHub
[https://github.com/fourseven/meteor-scss/issues/92#issuecomment-126447380] .[https://github.com/notifications/beacon/ABOopIqC8xE-J-7-wxAK2XqB_qgsVRQ5ks5oinJugaJpZM4EsBJb.gif]
