### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mccormjt** [fourseven/meteor-scss#93]
Currently you cannot use this package on windows:

 While checking for fourseven:scss@3.0.0:
 error: No compatible binary build found for this package. Contact the
 package author and ask them to publish it for your platform.

**Comment by mccormjt** [comment]
I apologize, this issue is fixed in 3.1 version.....havent updated it in a while, thanks!

**Comment by fourseven** [comment]
Thanks, yes 3.0.0 had an issue with node-sass which stopped it building on Windows.
