### ISSUE TITLE
"Scss compiler error: file to import not found or unreadable" (Windows)

### ISSUE THREAD

**Issue by fabyeah** [fourseven/meteor-scss#96]
Error on **startup**.

    C:/[...]/index.scss:6:9: Scss compiler
    error: file to import not found or unreadable: modules
    pplicant♀lientstyle.scss
    Current dir: C:/[...]

Note the weird/replaced characters ♀

This is what the **index.scss** looks like:

    @import "modules\applicant\client\style.scss";

    @import "modules\header\client\style.scss";
    @import "modules\landing\client\style.scss";

Not sure why there is a blank line. And Apparently it also skips and doesn't include my style.scss in the root folder (same folder as scss.json). 

And **scss.json**:

    {
	"useIndex": true,
	"enableAutoprefixer": true,
	"autoprefixerOptions": {
		"browsers": ["> 5%", "android >= 4.2", "ios >= 7"],
		"cascade": false
	}
    }

It worked with 2.1.1. Reverting for now...

**Comment by iamlasse** [comment]
How did you get it to work?

**Comment by fabyeah** [comment]
I'm using version 2.1.1

**Comment by iamlasse** [comment]
Just downgraded, will see if that resolves it. Thank you

On Saturday, June 27, 2015, fabyeah <notifications@github.com> wrote:

> I'm using version 2.1.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fourseven/meteor-scss/issues/96#issuecomment-116107973>
> .
>


-- 

Lasse Larsen
P: +1 323 344 2004
www.lasselarsen.me

*Connect with me*
Become my friend on facebook
<http://www.facebook.com/pages/Lasse-Larsen/31554704351>
You should follow me on twitter <http://www.twitter.com/lasse_larsen>

**Comment by fabyeah** [comment]
Seems to be fixed in 3.2.0!
