### ISSUE TITLE
Style.sass included inside itself on windows

### ISSUE THREAD

**Issue by iamlasse** [fourseven/meteor-scss#98]
When running on windows, style.sass (index file) gets included at the bottom of itself below all other files resulting in errors.

scss.json

{
  "enableAutoprefixer": true,
  "autoprefixerOptions": {
      "browsers": ["> 5%"],
      "cascade": false
  },
  "useIndex" : true,
  "indexFilePath" : "client/style.sass",
  "includePaths": [
  ".meteor/local/build/programs/server/assets/packages/yang2007chun_materialize-scss/bower_components/materialize/sass",
  "client/templates/*"
  ]
}

**Comment by mariocatch** [comment]
This is still occurring. It's also including the index file at the bottom of itself, which causes no styles to be applied to the site when ran.

**Comment by Octopixell** [comment]
Also described in #94. +1

**Comment by fourseven** [comment]
3.2.0 is released, please let me know if there's still an issue. You may need to re-write the index.scss file you use to utilize `/` instead of `\`

**Comment by sebakerckhof** [comment]
Closing, since not valid for current version anymore
